### ISSUE TITLE
Datapusher fails in staging with SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1188]
Staging has a GSA provided cert, which is not included in any bundled CAs but _is_ installed on all the hosts. For the `requests` package, you should be able to specify `REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt` in order for it to get picked up.

```
[Thu Dec 05 00:18:57.064070 2019] [:error] [pid 31335:tid 139743168055040] Job "push_to_datastore (trigger: RunTriggerNow, run = True, next run at: None)" raised an exception
[Thu Dec 05 00:18:57.064130 2019] [:error] [pid 31335:tid 139743168055040] Traceback (most recent call last):
[Thu Dec 05 00:18:57.064137 2019] [:error] [pid 31335:tid 139743168055040]   File "/usr/lib/datapusher/lib/python2.7/site-packages/apscheduler/scheduler.py", line 512, in _run_job
[Thu Dec 05 00:18:57.064142 2019] [:error] [pid 31335:tid 139743168055040]     retval = job.func(*job.args, **job.kwargs)
[Thu Dec 05 00:18:57.064147 2019] [:error] [pid 31335:tid 139743168055040]   File "/usr/lib/datapusher/src/datapusher/datapusher/jobs.py", line 317, in push_to_datastore
[Thu Dec 05 00:18:57.064151 2019] [:error] [pid 31335:tid 139743168055040]     resource = get_resource(resource_id, ckan_url, api_key)
[Thu Dec 05 00:18:57.064156 2019] [:error] [pid 31335:tid 139743168055040]   File "/usr/lib/datapusher/src/datapusher/datapusher/jobs.py", line 265, in get_resource
[Thu Dec 05 00:18:57.064160 2019] [:error] [pid 31335:tid 139743168055040]     'Authorization': api_key
[Thu Dec 05 00:18:57.064164 2019] [:error] [pid 31335:tid 139743168055040]   File "/usr/lib/datapusher/lib/python2.7/site-packages/requests/api.py", line 116, in post
[Thu Dec 05 00:18:57.064169 2019] [:error] [pid 31335:tid 139743168055040]     return request('post', url, data=data, json=json, **kwargs)
[Thu Dec 05 00:18:57.064173 2019] [:error] [pid 31335:tid 139743168055040]   File "/usr/lib/datapusher/lib/python2.7/site-packages/requests/api.py", line 60, in request
[Thu Dec 05 00:18:57.064178 2019] [:error] [pid 31335:tid 139743168055040]     return session.request(method=method, url=url, **kwargs)
[Thu Dec 05 00:18:57.064182 2019] [:error] [pid 31335:tid 139743168055040]   File "/usr/lib/datapusher/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
[Thu Dec 05 00:18:57.064186 2019] [:error] [pid 31335:tid 139743168055040]     resp = self.send(prep, **send_kwargs)
[Thu Dec 05 00:18:57.064190 2019] [:error] [pid 31335:tid 139743168055040]   File "/usr/lib/datapusher/lib/python2.7/site-packages/requests/sessions.py", line 668, in send
[Thu Dec 05 00:18:57.064195 2019] [:error] [pid 31335:tid 139743168055040]     history = [resp for resp in gen] if allow_redirects else []
[Thu Dec 05 00:18:57.064199 2019] [:error] [pid 31335:tid 139743168055040]   File "/usr/lib/datapusher/lib/python2.7/site-packages/requests/sessions.py", line 247, in resolve_redirects
[Thu Dec 05 00:18:57.064204 2019] [:error] [pid 31335:tid 139743168055040]     **adapter_kwargs
[Thu Dec 05 00:18:57.064208 2019] [:error] [pid 31335:tid 139743168055040]   File "/usr/lib/datapusher/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
[Thu Dec 05 00:18:57.064212 2019] [:error] [pid 31335:tid 139743168055040]     r = adapter.send(request, **kwargs)
[Thu Dec 05 00:18:57.064217 2019] [:error] [pid 31335:tid 139743168055040]   File "/usr/lib/datapusher/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
[Thu Dec 05 00:18:57.064221 2019] [:error] [pid 31335:tid 139743168055040]     raise SSLError(e, request=request)
[Thu Dec 05 00:18:57.064225 2019] [:error] [pid 31335:tid 139743168055040] SSLError: HTTPSConnectionPool(host='inventory-datagov.dev-ocsit.bsp.gsa.gov', port=443): Max retries exceeded with url: /api/3/action/resource_show (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
```

## How to reproduce

1. `service apache2 start`

## Expected behavior

Datapusher starts successfully and processes jobs.

## Actual behavior

Datapusher fails to process jobs with SSL: CERTIFICATE_VERIFY_FAILED error.

**Comment by jbrown-xentity** [comment]
Closing related to #2094
