### ISSUE TITLE
Uncaught Error: Call to undefined method stdClass::isValid() in SAML 2.0 Single Sign-On

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1276]
From WordPress email notification:
```
Error Details
=============
An error of type E_ERROR was caused in line 75 of the file /var/www/datagov/new/web/app/plugins/saml-20-single-sign-on/saml/lib/SimpleSAML/Auth/Simple.php. Error message: Uncaught Error: Call to undefined method stdClass::isValid() in /var/www/datagov/new/web/app/plugins/saml-20-single-sign-on/saml/lib/SimpleSAML/Auth/Simple.php:75
Stack trace:
#0 /var/www/datagov/new/web/app/plugins/saml-20-single-sign-on/lib/classes/saml_client.php(54): SimpleSAML_Auth_Simple->requireAuth(Array)
#1 /var/www/datagov/new/web/wp/wp-includes/class-wp-hook.php(288): SAML_Client->authenticate(NULL)
#2 /var/www/datagov/new/web/wp/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#3 /var/www/datagov/new/web/wp/wp-includes/plugin.php(531): WP_Hook->do_action(Array)
#4 /var/www/datagov/new/web/wp/wp-includes/user.php(67): do_action_ref_array('wp_authenticate', Array)
#5 /var/www/datagov/new/web/wp/wp-login.php(934): wp_signon(Array, '')
#6 {main}
  thrown
```

## How to reproduce

1. Description of steps to reproduce the issue.

**Comment by mogul** [comment]
@FuhuXia please look into (securely) expanding the repro steps here based on the mails where we've seen this reported.

**Comment by nickumia-reisys** [comment]
Wordpress no longer exists.  Data.gov is on cloud.gov now,
- https://github.com/GSA/data.gov/issues/3555
- https://github.com/GSA/data.gov/issues/3554
- https://github.com/GSA/data.gov/issues/2788
- https://github.com/GSA/data.gov/issues/3541
- https://github.com/GSA/data.gov/issues/3891
