### ISSUE TITLE
catalog-app fails to create virtulanev: 'ImportError: No module named zipp'

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1392]
```
Step 12/33 : RUN virtualenv -p /usr/local/lib/python$PYTHON_VERSION/bin/python $CKAN_HOME
 ---> Running in d0522e4b42fe
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 7, in <module>
    from virtualenv.__main__ import run_with_catch
  File "/usr/local/lib/python2.7/dist-packages/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run
  File "/usr/local/lib/python2.7/dist-packages/virtualenv/run/__init__.py", line 9, in <module>
    from .plugin.activators import ActivationSelector
  File "/usr/local/lib/python2.7/dist-packages/virtualenv/run/plugin/activators.py", line 6, in <module>
    from .base import ComponentBuilder
  File "/usr/local/lib/python2.7/dist-packages/virtualenv/run/plugin/base.py", line 9, in <module>
    from importlib_metadata import entry_points
  File "/usr/local/lib/python2.7/dist-packages/importlib_metadata/__init__.py", line 9, in <module>
    import zipp
ImportError: No module named zipp
```

## How to reproduce

1. `docker-compose build`

**Comment by adborden** [comment]
@jbrown-xentity pointed out https://github.com/pypa/virtualenv/issues/1630

**Comment by mogul** [comment]
We believe this is fixed.
