### ISSUE TITLE
Inventory-next: datapusher not working on migrated datastore DB

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2329]
Inventory-next datapusher is not working on DB migrated from inventory v1.

## How to reproduce

1. Login to inventorty-next on staging, create a dataset, upload a small csv file as resource.
2. Click on the resource.

## Expected behavior

See csv data in the Data Explorer

`/var/log/inventory/datapusher,error.log` show entries like this
```
Fetching from: https://inventory-next-datagov.dev-ocsit.bsp.gsa.gov/dataset/2bc38070-eb8f-45d0-8f9c-1a91932e0559/resource/e880aa9a-211e-4f0e-8e7f-d16e16bd1adf/download/del.csv
Determined headers and types: [{'type': 'numeric', 'id': 'a'}, {'type': 'numeric', 'id': 'b'}]
Saving chunk 0 (last)
Successfully pushed 1 entries to "e880aa9a-211e-4f0e-8e7f-d16e16bd1adf".
```

## Actual behavior

Error loading CSV data.

Error in `/var/log/inventory/datapusher,error.log`
```
Fetching from: https://inventory-next-datagov.dev-ocsit.bsp.gsa.gov/dataset/2bc38070-eb8f-45d0-8f9c-1a91932e0559/resource/d1a0ec07-908c-4695-a6ba-a8e1667f35c9/download/del.csv
Error notifying listener
Traceback (most recent call last):
  File "/usr/lib/datapusher/lib/python2.7/site-packages/apscheduler/scheduler.py", line 239, in _notify_listeners
    cb(event)
  File "/usr/lib/datapusher/lib/python2.7/site-packages/ckanserviceprovider/web.py", line 189, in job_listener
    db.mark_job_as_errored(job_id, error_object)
  File "/usr/lib/datapusher/lib/python2.7/site-packages/ckanserviceprovider/db.py", line 413, in mark_job_as_errored
    _update_job(job_id, update_dict)
  File "/usr/lib/datapusher/lib/python2.7/site-packages/ckanserviceprovider/db.py", line 348, in _update_job
    job_dict["error"] = json.dumps(job_dict["error"])
  File "/usr/local/lib/python2.7.16/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python2.7.16/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python2.7.16/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python2.7.16/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <Response [500]> is not JSON serializable
Job "push_to_datastore (trigger: RunTriggerNow, run = True, next run at: None)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/datapusher/lib/python2.7/site-packages/apscheduler/scheduler.py", line 512, in _run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/lib/datapusher/src/datapusher/datapusher/jobs.py", line 435, in push_to_datastore
    existing = datastore_resource_exists(resource_id, api_key, ckan_url)
  File "/usr/lib/datapusher/src/datapusher/datapusher/jobs.py", line 232, in datastore_resource_exists
    response.status_code, search_url, response,
HTTPError: Error getting datastore resource. status=500 url=https://inventory-next-datagov.dev-ocsit.bsp.gsa.gov/api/3/action/datastore_search response=<Response [500]>
```

**Comment by FuhuXia** [comment]
In the `/var/log/inventory/gunicorn.log`, these is this error:
```
ProgrammingError: (psycopg2.ProgrammingError) permission denied for relation _table_metadata
```

I think it is due to datastore DB permission difference between 2.5 and 2.8, or RDS snapshot not copying entire role permission. The fact that we are using separated DBs for datastore might also has something to do with this error.  Will re-run command [datastore set-permissions](https://docs.ckan.org/en/2.8/maintaining/datastore.html#set-permissions) to solve the issue.

**Comment by FuhuXia** [comment]
Issue resolved after run

`sudo ckan datastore set-permissions | PGPASSWORD=my-pw psql -h datastore-host -U my-user -d datastore-db-name`
