### ISSUE TITLE
Catalog "Filter by location" map is not working

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2338]
Catalog "Filter by location" map is not loading

## How to reproduce

1. https://catalog-next.sandbox.datagov.us/api/action/location_search?q=california

## Expected behavior

See map on the left "Filter by location" grid

## Actual behavior

Map grid is blank

**Comment by FuhuXia** [comment]
It seems to be introduced by latest release 20201015. Previous release (20201001) has no such issue.

**Comment by adborden** [comment]
On [sandbox](https://catalog-next.sandbox.datagov.us/dataset) the map is loading, but filtering does not work.

https://catalog-next.sandbox.datagov.us/api/action/location_search?q=california returns a 500.

**Comment by avdata99** [comment]
Error log

```
ERROR [ckan.views.api] (psycopg2.ProgrammingError) relation "locations" does not exist
LINE 2:             FROM locations
                         ^
 [SQL: 'SELECT id, display_name, ST_AsGeoJSON(the_geom) AS geom\n            FROM locations\n            WHERE lower(name) LIKE %(term)s\n            ORDER BY type_order, display_name'] [parameters: {'term': 'california%'}]
Traceback (most recent call last):
  File "/usr/lib/ckan-new/src/ckan/ckan/views/api.py", line 288, in action
    result = function(context, request_data)
  File "/usr/lib/ckan-new/src/ckan/ckan/logic/__init__.py", line 467, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan-new/src/ckanext-geodatagov/ckanext/geodatagov/logic.py", line 52, in location_search
    q = model.Session.execute(sql, {'term': '{0}%'.format(term.lower())})
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1139, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/newrelic/hooks/database_psycopg2.py", line 65, in execute
    **kwargs)
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/newrelic/hooks/database_dbapi2.py", line 39, in execute
    *args, **kwargs)
ProgrammingError: (psycopg2.ProgrammingError) relation "locations" does not exist
LINE 2:             FROM locations
                         ^
 [SQL: 'SELECT id, display_name, ST_AsGeoJSON(the_geom) AS geom\n            FROM locations\n            WHERE lower(name) LIKE %(term)s\n            ORDER BY type_order, display_name'] [parameters: {'term': 'california%'}]

``

**Comment by FuhuXia** [comment]
There should be a one-time task to add the `locations` table. It can be copied from catalog v1 databases.
