### ISSUE TITLE
saml_error parsing logout request

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2530]
In /tmp/sp.log
```
2020-12-08 19:08:35,639 saml2.s2repoze.plugins.sp:ERROR [sp.identify] saml_error
Traceback (most recent call last):
  File "/usr/lib/ckan-new/src/pysaml2/src/saml2/s2repoze/plugins/sp.py", line 533, in identify
    post["SAMLResponse"][0], binding
  File "/usr/lib/ckan-new/src/pysaml2/src/saml2/entity.py", line 1221, in parse_logout_request_response
    "single_logout_service", binding)
  File "/usr/lib/ckan-new/src/pysaml2/src/saml2/entity.py", line 1129, in _parse_response
    xmlstr = self.unravel(xmlstr, binding, response_cls.msgtype)
  File "/usr/lib/ckan-new/src/pysaml2/src/saml2/entity.py", line 391, in unravel
    raise UnravelError("Unravelling binding '%s' failed" % binding)
```

## How to reproduce

1. Description of steps to reproduce the issue.

**Comment by nickumia-reisys** [comment]
Looks suspiciously similar to another bug we fixed,
- https://github.com/GSA/data.gov/issues/3708

But we are on upstream and we have no issues currently,
- https://github.com/GSA/data.gov/issues/3939
