### ISSUE TITLE
Deploy catalog application on cloud.gov

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#2604]
## User Story

In order to reduce the operation and maintenance burden of catalog.data.gov, the data.gov team wants the catalog.data.gov application deployed on cloud.gov.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] WHEN I commit a change to the `main` branch in the `GSA/catalog.data.gov repository` \
  AND I browse to [the CircleCI dashboard](https://app.circleci.com/pipelines/github/GSA/catalog.data.gov)
  THEN I see a deployment pipeline kick off \
  AND the pipeline completes successfully \
  AND the change is visible at https://catalog-data-gov.app.cloud.gov
- [x] If any manual preparation of the target space was necessary, then an issue exists about automating that setup in future.

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]
We are deploying from the `main` branch to the `gsa-datagov/production` space only. Other branches and spaces are considered out of scope here. Note cronjobs are also out of scope for now.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]
None. This work is being done in an environment completely separate from the existing deployment, and only open source and open data are implied.

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

- [x] Rename the `master` branch if necessary
- [x] Bring any existing cloud-gov branch up to date
- [x] Create any necessary services in the target space with `cf create-service`
- [x] Create a manifest.yml capturing any settings or bindings
- [x] Practice a hand-driven deployment
- [x] Ensure environment settings are installed from `$VCAP_SERVICES`
- [x] Make sure the health check is correct and passing
- [x] Make sure the homepage comes up
- [x] The README.md should have instructions for hand-deployment
- [x] Add CircleCI or GitHub Action config for deployment to the `production` space
- [x] Get login.gov saml2auth working ([issue created](https://github.com/GSA/datagov-deploy/issues/2809))
- [x] Create catalog workers ([made issue todo](https://github.com/GSA/datagov-deploy/issues/2810))
- [x] Create secret user-provided-service per environment and add secrets (beaker, site_id, etc) [PR](https://github.com/GSA/catalog.data.gov/pull/243)
- [x] Initialize extensions (harvester, archiver, qa) ([PR](https://github.com/GSA/catalog.data.gov/pull/242))
- [x] Use gunicorn as web service ([PR](https://github.com/GSA/catalog.data.gov/pull/242))

**Comment by adborden** [comment]
@jbrown-xentity:
- Renamed the branch master -> main
- Added GH environments and ci-deployer keys for development, staging, and production.
- Deployed a new ssb that should create superusers for postgres, but it did not work and is now blocking any application bind which will break inventory too. Opened https://github.com/GSA/datagov-ssb/pull/24 to rollback.

Can you post the error you were running into? From the docs, it looks like AWS RDS doesn't create superusers but still allows extension creation somehow. I can't find any docs to reference, but maybe we should try creating a [medium instance](https://github.com/GSA/catalog-app/compare/bionic#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R178) before digging more into tweaking the CSB again.

**Comment by jbrown-xentity** [comment]
Created a medium instance through the csb, same issue (`cf create-service csb-aws-postgresql medium ${app_name}-db -c '{"postgres_version": "9.6", "publicly_accessible": true, "storage_encrypted": true}'`). Logs from the installation step are below. Will dig in more...

```
<SQL>
05:49:13.231: [APP/PROC/WEB.0] CREATE EXTENSION IF NOT EXISTS postgis;
05:49:13.231: [APP/PROC/WEB.0] CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
05:49:13.231: [APP/PROC/WEB.0] CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;
05:49:13.231: [APP/PROC/WEB.0] CREATE EXTENSION IF NOT EXISTS postgis_topology;
05:49:13.231: [APP/PROC/WEB.0] ALTER SCHEMA tiger OWNER TO "FIUhDtjNSHQyEYWl";
05:49:13.231: [APP/PROC/WEB.0] ALTER SCHEMA tiger_data OWNER TO "FIUhDtjNSHQyEYWl";
05:49:13.231: [APP/PROC/WEB.0] ALTER SCHEMA topology OWNER TO "FIUhDtjNSHQyEYWl";
05:49:13.231: [APP/PROC/WEB.0] CREATE FUNCTION exec(text) RETURNS text LANGUAGE PLPGSQL VOLATILE AS $f$ BEGIN EXECUTE $1; RETURN $1; END; $f$;                              
05:49:13.231: [APP/PROC/WEB.0] SELECT exec('ALTER TABLE ' || quote_ident(s.nspname) || '.' || quote_ident(s.relname) || ' OWNER TO "FIUhDtjNSHQyEYWl";')
05:49:13.231: [APP/PROC/WEB.0]     FROM (
05:49:13.231: [APP/PROC/WEB.0]         SELECT nspname, relname
05:49:13.231: [APP/PROC/WEB.0]         FROM pg_class c JOIN pg_namespace n ON (c.relnamespace = n.oid) 
05:49:13.231: [APP/PROC/WEB.0]         WHERE nspname IN ('tiger','topology', 'tiger_data') AND
05:49:13.231: [APP/PROC/WEB.0]     relkind IN ('r','S','v') ORDER BY relkind = 'S')
05:49:13.231: [APP/PROC/WEB.0] s;  
05:49:13.231: [APP/PROC/WEB.0] SET search_path=public,tiger;
05:49:13.231: [APP/PROC/WEB.0] </SQL>
05:49:13.235: [APP/PROC/WEB.0] Exception while executing SQL: permission denied to create extension "postgis"
05:49:13.235: [APP/PROC/WEB.0] HINT:  Must be superuser to create this extension.
```

**Comment by jbrown-xentity** [comment]
[The docs seem pretty clear](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.PostgreSQL.CommonDBATasks.PostGIS.html), must be the super-user. Going to make sure username password are setup appropriately in the script...

**Comment by jbrown-xentity** [comment]
After further research, it seems like [the csb does not have superuser privileges](https://github.com/cloudfoundry-incubator/csb-brokerpak-aws/blob/main/terraform/rds/bind/postgresql/main.tf) ([terraform docs say superuser must be defined](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest/docs/resources/postgresql_role)). Just not sure how to get around this... Trying the native cloud.gov postgres rds just to validate will not work, and will document the bug more fully if it arises.

**Comment by jbrown-xentity** [comment]
According to [recent CKAN community discussions](https://github.com/ckan/ckan/issues/5796#issuecomment-759932941), it might be possible to get around this by moving to sqlalchemy 1.2 and vdm 0.15. Testing...

**Comment by jbrown-xentity** [comment]
The original error with sqlalchemy 1.1 and postgres 12 is

```
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column cons.consrc does not exist
07:05:56.598: [APP/PROC/WEB.0] LINE 4:                 cons.consrc as src
07:05:56.598: [APP/PROC/WEB.0]                         ^
07:05:56.598: [APP/PROC/WEB.0] HINT:  Perhaps you meant to reference the column "cons.conkey" or the column "cons.conbin".
07:05:56.598: [APP/PROC/WEB.0]  [SQL: "\n            SELECT\n                cons.conname as name,\n                cons.consrc as src\n            FROM\n                pg_catalog.pg_constraint cons\n            WHERE\n                cons.conrelid = %(table_oid)s AND\n                cons.contype = 'c'\n        "] [parameters: {'table_oid': 18002}]
```
Installed sqlachemy 1.2 and vdm 0.15 per discussions, and failed with the following error:
```
07:11:14.299: [APP/PROC/WEB.0] Exception happened during processing of request from ('10.255.75.178', 35590)
07:11:14.300: [RTR.4] catalog-sleepy-cheetah-ag.app.cloud.gov - [2021-02-10T14:11:14.185850913Z] "GET /dataset HTTP/1.1" 500 0 22 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36" "127.0.0.1:62934" "10.10.2.9:61056" x_forwarded_for:"162.246.46.239, 127.0.0.1" x_forwarded_proto:"https" vcap_request_id:"b2858bd7-0747-4435-606a-8efbb4d90049" response_time:0.113555 gorouter_time:0.000132 app_id:"81eb5077-6880-4fdf-b734-8ae1e8c88113" app_index:"0" x_cf_routererror:"-" x_b3_traceid:"2f0e4f8164c56b5d" x_b3_spanid:"2f0e4f8164c56b5d" x_b3_parentspanid:"-" b3:"2f0e4f8164c56b5d-2f0e4f8164c56b5d"

07:11:14.300: [APP/PROC/WEB.0]     self.finish_request(request, client_address)
07:11:14.300: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/SocketServer.py", line 334, in finish_request
07:11:14.301: [APP/PROC/WEB.0]     self.RequestHandlerClass(request, client_address, self)
07:11:14.301: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/SocketServer.py", line 655, in __init__
07:11:14.301: [APP/PROC/WEB.0]     self.handle()
07:11:14.301: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/paste/httpserver.py", line 442, in handle
07:11:14.301: [APP/PROC/WEB.0]     BaseHTTPRequestHandler.handle(self)
07:11:14.301: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/BaseHTTPServer.py", line 340, in handle
07:11:14.301: [APP/PROC/WEB.0]     self.handle_one_request()
07:11:14.301: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/paste/httpserver.py", line 437, in handle_one_request
07:11:14.301: [APP/PROC/WEB.0]     self.wsgi_execute()
07:11:14.301: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/paste/httpserver.py", line 287, in wsgi_execute
07:11:14.301: [APP/PROC/WEB.0]     self.wsgi_start_response)
07:11:14.301: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/src/ckan/ckan/config/middleware/__init__.py", line 210, in __call__
07:11:14.301: [APP/PROC/WEB.0]     return self.apps[app_name](environ, start_response)
07:11:14.301: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/src/ckan/ckan/config/middleware/common_middleware.py", line 96, in __call__
07:11:14.301: [APP/PROC/WEB.0]     return self.app(environ, start_response)
07:11:14.303: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/src/ckan/ckan/config/middleware/common_middleware.py", line 115, in __call__
07:11:14.303: [APP/PROC/WEB.0]     return self.app(environ, start_response)
07:11:14.303: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/paste/cascade.py", line 130, in __call__
07:11:14.303: [APP/PROC/WEB.0]     return self.apps[-1](environ, start_response)
07:11:14.303: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/paste/registry.py", line 379, in __call__
07:11:14.303: [APP/PROC/WEB.0]     app_iter = self.application(environ, start_response)
07:11:14.303: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/repoze/who/middleware.py", line 86, in __call__
07:11:14.304: [APP/PROC/WEB.0]     app_iter = app(environ, wrapper.wrap_start_response)
07:11:14.304: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/pylons/middleware.py", line 214, in __call__
07:11:14.304: [APP/PROC/WEB.0]     self.app, new_environ, catch_exc_info=True)
07:11:14.304: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/pylons/util.py", line 94, in call_wsgi_application
07:11:14.304: [APP/PROC/WEB.0]     app_iter = application(environ, start_response)
07:11:14.305: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/weberror/errormiddleware.py", line 165, in __call__
07:11:14.306: [APP/PROC/WEB.0]     return self.application(environ, start_response)
07:11:14.306: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/src/webob/webob/dec.py", line 147, in __call__
07:11:14.306: [APP/PROC/WEB.0]     resp = self.call_func(req, *args, **self.kwargs)
07:11:14.306: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/src/webob/webob/dec.py", line 208, in call_func
07:11:14.306: [APP/PROC/WEB.0]     return self.func(req, *args, **kwargs)
07:11:14.306: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/fanstatic/publisher.py", line 234, in __call__
07:11:14.306: [APP/PROC/WEB.0]     return request.get_response(self.app)
07:11:14.306: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/src/webob/webob/request.py", line 1053, in get_response
07:11:14.306: [APP/PROC/WEB.0]     application, catch_exc_info=False)
07:11:14.307: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/src/webob/webob/request.py", line 1022, in call_application
07:11:14.307: [APP/PROC/WEB.0]     app_iter = application(self.environ, start_response)
07:11:14.307: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/src/webob/webob/dec.py", line 147, in __call__
07:11:14.307: [APP/PROC/WEB.0]     resp = self.call_func(req, *args, **self.kwargs)
07:11:14.307: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/src/webob/webob/dec.py", line 208, in call_func
07:11:14.307: [APP/PROC/WEB.0]     return self.func(req, *args, **kwargs)
07:11:14.307: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/fanstatic/injector.py", line 54, in __call__
07:11:14.307: [APP/PROC/WEB.0]     response = request.get_response(self.app)
07:11:14.307: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/src/webob/webob/request.py", line 1053, in get_response
07:11:14.307: [APP/PROC/WEB.0]     application, catch_exc_info=False)
07:11:14.307: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/src/webob/webob/request.py", line 1022, in call_application
07:11:14.307: [APP/PROC/WEB.0]     app_iter = application(self.environ, start_response)
07:11:14.307: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/src/ckan/ckan/config/middleware/pylons_app.py", line 264, in inner
07:11:14.307: [APP/PROC/WEB.0]     result = application(environ, start_response)
07:11:14.307: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/beaker/middleware.py", line 73, in __call__
07:11:14.308: [APP/PROC/WEB.0]     return self.app(environ, start_response)
07:11:14.308: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
07:11:14.308: [APP/PROC/WEB.0]     return self.wrap_app(environ, session_start_response)
07:11:14.308: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/routes/middleware.py", line 131, in __call__
07:11:14.308: [APP/PROC/WEB.0]     response = self.app(environ, start_response)
07:11:14.308: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/src/ckan/ckan/config/middleware/common_middleware.py", line 33, in __call__
07:11:14.308: [APP/PROC/WEB.0]     return self.app(environ, start_response)
07:11:14.308: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/src/ckan/ckan/config/middleware/common_middleware.py", line 59, in __call__
07:11:14.308: [APP/PROC/WEB.0]     return self.app(environ, start_response)
07:11:14.308: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/pylons/wsgiapp.py", line 125, in __call__
07:11:14.311: [APP/PROC/WEB.0]     response = self.dispatch(controller, environ, start_response)
07:11:14.311: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/pylons/wsgiapp.py", line 324, in dispatch
07:11:14.311: [APP/PROC/WEB.0]     return controller(environ, start_response)
07:11:14.311: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/src/ckan/ckan/lib/base.py", line 242, in __call__
07:11:14.311: [APP/PROC/WEB.0]     res = WSGIController.__call__(self, environ, start_response)
07:11:14.311: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/pylons/controllers/core.py", line 221, in __call__
07:11:14.311: [APP/PROC/WEB.0]     response = self._dispatch_call()
07:11:14.311: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/pylons/controllers/core.py", line 172, in _dispatch_call
07:11:14.311: [APP/PROC/WEB.0]     response = self._inspect_call(func)
07:11:14.311: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/pylons/controllers/core.py", line 107, in _inspect_call
07:11:14.311: [APP/PROC/WEB.0]     result = self._perform_call(func, args)
07:11:14.311: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/pylons/controllers/core.py", line 60, in _perform_call
07:11:14.311: [APP/PROC/WEB.0]     return func(**args)
07:11:14.311: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/src/ckan/ckan/controllers/error.py", line 50, in document
07:11:14.311: [APP/PROC/WEB.0]     return render('error_document_template.html', extra_vars=extra_vars)
07:11:14.312: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/src/ckan/ckan/lib/base.py", line 126, in render
07:11:14.312: [APP/PROC/WEB.0]     *pargs, **kwargs)
07:11:14.312: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/src/ckan/ckan/lib/base.py", line 188, in _pylons_prepare_renderer
07:11:14.312: [APP/PROC/WEB.0]     elif session.last_accessed:
07:11:14.312: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/werkzeug/local.py", line 348, in __getattr__
07:11:14.312: [APP/PROC/WEB.0]     return getattr(self._get_current_object(), name)
07:11:14.312: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/paste/registry.py", line 137, in __getattr__
07:11:14.312: [APP/PROC/WEB.0]     return getattr(self._current_obj(), attr)
07:11:14.312: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/beaker/session.py", line 814, in __getattr__
07:11:14.312: [APP/PROC/WEB.0] ----------------------------------------
07:11:14.312: [APP/PROC/WEB.0]     return getattr(self._session(), attr)
07:11:14.312: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/beaker/session.py", line 810, in _session
07:11:14.312: [APP/PROC/WEB.0]     self.__dict__['_sess'] = session_cls(req, **params)
07:11:14.312: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/beaker/session.py", line 183, in __init__
07:11:14.312: [APP/PROC/WEB.0]     self.namespace_class = namespace_class or clsmap[self.type]
07:11:14.312: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/beaker/cache.py", line 79, in __getitem__
07:11:14.312: [APP/PROC/WEB.0]     raise e
07:11:14.312: [APP/PROC/WEB.0] KeyError: "'ext:database'"
```

Tried getting around this by installing latest sqlalchemy 1.2 as [Queensland gov did on their fork of CKAN](https://github.com/qld-gov-au/ckan/commit/a7eeb6b9bf1df29fe231af1ffb419f16b0d299e6) without vdm change, and got error:
```
File "/home/vcap/deps/0/bin/paster", line 10, in <module>
07:34:11.297: [APP/PROC/WEB.0]     sys.exit(run())
07:34:11.297: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/paste/script/command.py", line 101, in run
07:34:11.297: [APP/PROC/WEB.0]     command = commands[command_name].load()
07:34:11.297: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
07:34:11.297: [APP/PROC/WEB.0]     return self.resolve()
07:34:11.297: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
07:34:11.297: [APP/PROC/WEB.0]     module = __import__(self.module_name, fromlist=['__name__'], level=0)
07:34:11.297: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/src/ckan/ckan/lib/cli.py", line 32, in <module>
07:34:11.297: [APP/PROC/WEB.0]     from ckan.config.middleware import make_app
07:34:11.297: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/src/ckan/ckan/config/middleware/__init__.py", line 12, in <module>
07:34:11.297: [APP/PROC/WEB.0]     from ckan.config.environment import load_environment
07:34:11.297: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/src/ckan/ckan/config/environment.py", line 16, in <module>
07:34:11.297: [APP/PROC/WEB.0]     import ckan.model as model
07:34:11.297: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/src/ckan/ckan/model/__init__.py", line 9, in <module>
07:34:11.297: [APP/PROC/WEB.0]     import vdm.sqlalchemy
07:34:11.297: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/vdm/sqlalchemy/__init__.py", line 32, in <module>
07:34:11.297: [APP/PROC/WEB.0]     from tools import Repository
07:34:11.297: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/vdm/sqlalchemy/tools.py", line 34, in <module>
07:34:11.297: [APP/PROC/WEB.0]     raise ValueError("VDM only works with SQLAlchemy versions 0.4 through 0.9, not: %s" % sqav)
07:34:11.297: [APP/PROC/WEB.0] ValueError: VDM only works with SQLAlchemy versions 0.4 through 0.9, not: 1.2.19
```
Noting that upgrading vdm and sqlalchemy initially worked; database migrations happened and the app came online. As soon as the web route was hit the logged errors occurred...

Leaving this for now.

**Comment by adborden** [comment]
@jbrown-xentity the datagov-ssb service is updated with the role change. After a restart, the app was able to create the postgis extension successfully. This is the error I'm seeing now. It's possible this is specific to my scrap branch, so give it another push and take a look.

```
   2021-02-10T17:38:39.63-0800 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2021-02-10T17:38:39.63-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/bin/paster", line 10, in <module>
   2021-02-10T17:38:39.63-0800 [APP/PROC/WEB/0] ERR     sys.exit(run())
   2021-02-10T17:38:39.63-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
   2021-02-10T17:38:39.63-0800 [APP/PROC/WEB/0] ERR     invoke(command, command_name, options, args[1:])
   2021-02-10T17:38:39.63-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
   2021-02-10T17:38:39.63-0800 [APP/PROC/WEB/0] ERR     exit_code = runner.run(args)
   2021-02-10T17:38:39.63-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
   2021-02-10T17:38:39.63-0800 [APP/PROC/WEB/0] ERR     result = self.command()
   2021-02-10T17:38:39.63-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/ckan/ckan/lib/cli.py", line 357, in command
   2021-02-10T17:38:39.63-0800 [APP/PROC/WEB/0] ERR     self._load_config(cmd!='upgrade')
   2021-02-10T17:38:39.63-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/ckan/ckan/lib/cli.py", line 330, in _load_config
   2021-02-10T17:38:39.63-0800 [APP/PROC/WEB/0] ERR     self.site_user = load_config(self.options.config, load_site_user)
   2021-02-10T17:38:39.63-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/ckan/ckan/lib/cli.py", line 243, in load_config
   2021-02-10T17:38:39.63-0800 [APP/PROC/WEB/0] ERR     app = make_app(conf.global_conf, **conf.local_conf)
   2021-02-10T17:38:39.63-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/ckan/ckan/config/middleware/__init__.py", line 58, in make_app
   2021-02-10T17:38:39.63-0800 [APP/PROC/WEB/0] ERR     **app_conf)
   2021-02-10T17:38:39.63-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/ckan/ckan/config/middleware/pylons_app.py", line 121, in make_pylons_stack
   2021-02-10T17:38:39.63-0800 [APP/PROC/WEB/0] ERR     who_parser.parse(open(app_conf['who.config_file']))
   2021-02-10T17:38:39.63-0800 [APP/PROC/WEB/0] ERR IOError: [Errno 2] No such file or directory: '/home/vcap/app/ckan/setup/who.ini'
   ```

**Comment by jbrown-xentity** [comment]
Got a working version of catalog after working through some configuration issues... [PR is ready](https://github.com/GSA/catalog.data.gov/pull/235)! Will start from this point on a new PR for github actions and deploying to different environments...

**Comment by jbrown-xentity** [comment]
Example of completion; when updating documentation around db changes, the [app redeployed](https://github.com/GSA/catalog.data.gov/actions/runs/578434579).
