### ISSUE TITLE
inventory-next datapusher error on Excel xlsx files

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2699]
Uploading an Excel XLSX file as a resource to inventory-next dataset generates an error in datapusher log. As a result, spreadsheet data cannot be viewed in Data Explorer.

## How to reproduce

Choose any XLSX file to upload to inventory-next.sandbox.datagov.us as dataset resource. 

## Expected behavior

Data can be viewed in Data Explorer.

## Actual behavior

Data can NOT be viewed in Data Explorer. Error in `/var/log/inventory/datapusher.error.log`
```
Fetching from: https://inventory-next.sandbox.datagov.us/dataset/e6806e72-40d4-44ea-9587-926e1

Error notifying listener
Traceback (most recent call last):
  File "/usr/lib/datapusher/lib/python2.7/site-packages/apscheduler/scheduler.py", line 239, i

    cb(event)
  File "/usr/lib/datapusher/lib/python2.7/site-packages/ckanserviceprovider/web.py", line 189,

    db.mark_job_as_errored(job_id, error_object)
  File "/usr/lib/datapusher/lib/python2.7/site-packages/ckanserviceprovider/db.py", line 413,

    _update_job(job_id, update_dict)
  File "/usr/lib/datapusher/lib/python2.7/site-packages/ckanserviceprovider/db.py", line 347,

    job_dict["error"] = _validate_error(job_dict["error"])
  File "/usr/lib/datapusher/lib/python2.7/site-packages/ckanserviceprovider/db.py", line 323,

    "error['message'] must be a string")
InvalidErrorObjectError: error['message'] must be a string
Job "push_to_datastore (trigger: RunTriggerNow, run = True, next run at: None)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/datapusher/lib/python2.7/site-packages/apscheduler/scheduler.py", line 512, in _run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/lib/datapusher/src/datapusher/datapusher/jobs.py", line 428, in push_to_datastore
    raise util.JobError(e)
JobError: ("Can't read Excel file: XLRDError('Excel xlsx file; not supported',)", <traceback object at 0x7f031c735830>)
```
## Sketch
Inventory classic is fine. Only inventory-next has this error.

## Work-around
Open the XLSX file in Excel and save it as a CSV file. Upload the CSV file as resource.

**Comment by mogul** [comment]
Choosing to icebox for now because it need not block launch of inventory 2.8, and affects only a subset of users (at GSA).

**Comment by pjsharpe07** [comment]
We confirmed that this is still present during the inventory-next rollout

**Comment by FuhuXia** [comment]
Still an issue after Inventory 2.8 roll out. Datapusher can handle `csv`, `xls` files, not `xlsx` files.

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710

And even though datapusher is no longer around, issues like these make me curious about it's history.
