### ISSUE TITLE
Inventory cannot create session, returns 500 for all pages

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2783]
This started after the introduction of [ckanext-envvars](https://github.com/GSA/inventory-app/pull/233). API works fine, so our smoke test didn't catch this.

```
   2021-02-11T08:48:54.29-0800 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/python/lib/python2.7/site-packages/beaker/session.py:750: BeakerWarning: Invalidating corrupt session 24412380463f46218b4125d77bf85ba7; error was: (psycopg2.OperationalError) could not translate host name "db" to address: Name or service not known
```

and 

```
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR [2021-02-11 16:48:54 +0000] [201] [ERROR] Error handling request /
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 56, in handle
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     self.handle_request(listener_name, req, client, addr)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     addr)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     respiter = self.wsgi(environ, resp.start_response)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/ckan/ckan/config/middleware/__init__.py", line 202, in __call__
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     return self.apps[app_name](environ, start_response)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/ckan/ckan/config/middleware/common_middleware.py", line 115, in __call__
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     return self.app(environ, start_response)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/repoze/who/middleware.py", line 86, in __call__
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     app_iter = app(environ, wrapper.wrap_start_response)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/webob/webob/dec.py", line 147, in __call__
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     resp = self.call_func(req, *args, **self.kwargs)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/webob/webob/dec.py", line 208, in call_func
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     return self.func(req, *args, **kwargs)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/fanstatic/publisher.py", line 234, in __call__
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     return request.get_response(self.app)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/webob/webob/request.py", line 1053, in get_response
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     application, catch_exc_info=False)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/webob/webob/request.py", line 1022, in call_application
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     app_iter = application(self.environ, start_response)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/webob/webob/dec.py", line 147, in __call__
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     resp = self.call_func(req, *args, **self.kwargs)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/webob/webob/dec.py", line 208, in call_func
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     return self.func(req, *args, **kwargs)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/fanstatic/injector.py", line 54, in __call__
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     response = request.get_response(self.app)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/webob/webob/request.py", line 1053, in get_response
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     application, catch_exc_info=False)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/webob/webob/request.py", line 1022, in call_application
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     app_iter = application(self.environ, start_response)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     return self.wsgi_app(environ, start_response)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     return self.wrap_app(environ, session_start_response)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     response = self.handle_exception(e)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/flask/app.py", line 1547, in handle_exception
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     return self.finalize_request(handler(e), from_error_handler=True)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/ckan/ckan/config/middleware/flask_app.py", line 453, in error_handler
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     return base.render(u'error_document_template.html', extra_vars), 500
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/ckan/ckan/lib/base.py", line 129, in render
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     return flask_render_template(template_name, **extra_vars)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     context, ctx.app)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     rv = template.render(context)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     return self.environment.handle_exception(exc_info, True)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     reraise(exc_type, exc_value, tb)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/ckan/ckan/templates/error_document_template.html", line 1, in top-level template code
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     {% extends "page.html" %}
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/ckan/ckan/templates/page.html", line 1, in top-level template code
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     {% extends "base.html" %}
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/ckanext-usmetadata/ckanext/usmetadata/templates/base.html", line 1, in top-level template code
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     {% ckan_extends %}
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/ckanext-googleanalyticsbasic/ckanext/googleanalyticsbasic/templates/base.html", line 1, in top-level template code
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     {% ckan_extends %}
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/ckan/ckan/templates/base.html", line 101, in top-level template code
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     {%- block page %}{% endblock -%}
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/ckan/ckan/templates/page.html", line 19, in block "page"
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     {%- block content %}
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/ckan/ckan/templates/page.html", line 22, in block "content"
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     {% block main_content %}
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/ckan/ckan/templates/page.html", line 23, in block "main_content"
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     {% block flash %}
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/ckan/ckan/templates/error_document_template.html", line 18, in block "flash"
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     {% set flash_messages = h.flash.pop_messages() %}
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/src/ckan/ckan/lib/helpers.py", line 675, in pop_messages
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     messages = session.pop(self.session_key, [])
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/werkzeug/local.py", line 348, in __getattr__
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     return getattr(self._get_current_object(), name)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/werkzeug/local.py", line 348, in __getattr__
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     return getattr(self._get_current_object(), name)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] OUT 10.255.43.41 - - [11/Feb/2021:16:48:54 +0000] "GET / HTTP/1.1" 500 0 "-" "-"
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/beaker/session.py", line 754, in __getattr__
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     return getattr(self._session(), attr)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/beaker/session.py", line 750, in _session
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     self.__dict__['_sess'] = session_cls(req, **params)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/beaker/session.py", line 216, in __init__
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     self.invalidate()
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/beaker/session.py", line 365, in invalidate
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     self.load()
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/beaker/session.py", line 372, in load
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     **self.namespace_args)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/beaker/ext/database.py", line 101, in __init__
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     self.cache = DatabaseNamespaceManager.tables.get(table_key, make_cache)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/beaker/util.py", line 171, in get
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     return self.sync_get(key, createfunc, *args, **kwargs)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/beaker/util.py", line 182, in sync_get
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     return self._create(key, createfunc, *args, **kwargs)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/beaker/util.py", line 189, in _create
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     self[key] = obj = createfunc(*args, **kwargs)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/beaker/ext/database.py", line 94, in make_cache
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     schema=schema_name if schema_name else meta.schema
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 421, in __new__
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR     "existing Table object." % key)
   2021-02-11T08:48:54.36-0800 [APP/PROC/WEB/0] ERR InvalidRequestError: Table 'beaker_cache' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
```

It looks like maybe the URL passed to beaker is not coming from the environment (CKAN_SQLALCHEMY_URL). This should work, so I'm not sure what's going on here.
```
beaker.session.url=%(sqlalchemy.url)s
```

## How to reproduce

1. https://inventory-prod-datagov.app.cloud.gov/

## Expected behavior

Redirect to login, or a 401 Unauthorized.

## Actual behavior

Internal Server Error (500)

## Sketch
- [ ]  Identify the issue with beaker
- [ ] Update smoke test to test /dataset (this should be a 302, but for now is a 200)

**Comment by adborden** [comment]
Note that the behavior is different in incognito window, so this might be related to existing sessions? In an incognito window / fails but /dataset and /organization seem to load correctly.

In my browser, / /dataset and /organization all result in an error.

@jbrown-xentity you didn't add the beaker secret, yet, did you?

**Comment by jbrown-xentity** [comment]
> @jbrown-xentity you didn't add the beaker secret, yet, did you?

I did not, still pending
