### ISSUE TITLE
Inventory gives exceptions.KeyError when uploading resources

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2907]
For one particular dataset on Inventory production, when uploading a resource, the server gives an error. 

User sees:
```
Server Error - Refresh the Page: An internal server error occurred. Try refreshing the page by pressing F5 or Ctrl+F5.
```

Error logged in gunicorn.log:
```
2021-02-26 16:21:40,866 DEBUG [ckanext.usmetadata.plugin] update_package_schema
2021-02-26 16:21:40,866 DEBUG [ckanext.usmetadata.plugin] _modify_package_schema_update called
Error - <type 'exceptions.KeyError'>: 'resources'
2021-02-26 16:21:40,997 INFO  [ckan.lib.base]  /dataset/new_resource/networx-business-volume-fy2021%2C-1st-qtr render time 0.050 seconds
2021-02-26 16:21:41,218 INFO  [ckan.lib.base]  /api/i18n/en render time 0.003 seconds
```

## How to reproduce

Upload a resource to dataset https://inventory.data.gov/dataset/a4b28422-5ed4-4719-866a-111f1a9a61b1

## Expected behavior

Resource added successfully

## Actual behavior

Error seen on the UI and in the server log.

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by FuhuXia** [comment]
Retried on inventory after inventory-next went live. Issue still exists but a meaningful error message is logged. 
```
2021-03-04 14:34:02,556 ERROR [ckan.views.api] string indices must be integers
Traceback (most recent call last):
  File "/usr/lib/ckan-new/src/ckan/ckan/views/api.py", line 288, in action
    result = function(context, request_data)
  File "/usr/lib/ckan-new/src/ckan/ckan/logic/__init__.py", line 471, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan-new/src/ckan/ckan/logic/action/create.py", line 322, in resource_create
    raise ValidationError(e.error_dict)
  File "/usr/lib/ckan-new/src/ckan/ckan/logic/__init__.py", line 75, in __init__
    tag_errors.append(', '.join(error['name']))
TypeError: string indices must be integers
```
It indicates something to do with the dataset containing a `','` char in the machine name `networx-business-volume-fy2021,-1st-qtr`. Manually changed the machine name to remove the `','` and upload is successful. 

Will notify user the workaround, and update the title to reflect the real issue.

**Comment by FuhuXia** [comment]
Machine name issue is tracked at https://github.com/GSA/datagov-deploy/issues/2933.

**Comment by mogul** [comment]
Fuhu says this is being resolved via this other issue.
