### ISSUE TITLE
CKAN user can login without credentials after logged out

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3024]
After a user logs out or timed out, the session on IdP side is not affected. If the IdP session is still alive, clicking the login button will be able to log user in without any credentials. 

## How to reproduce

Log into a CKAN app on cloud.gov.
Click button to log out.
Click login button.

## Expected behavior
Prompted for credentials

## Actual behavior
Log in without credentials

## Sketch
A feature request is created in [ckanext-saml2auth](https://github.com/keitaroinc/ckanext-saml2auth/issues/49). 

A simple workaround could be giving a logout message:
```
You are now logged out of catalog.data.gov/inventory.data.gov,
however this has not logged you out of login.gov SAML. 
Click [here](https://secure.login.gov/logout) to log out login.gov.
```

**Comment by FuhuXia** [comment]
FYI, **SingleLogoutService** feature has been released by login.gov on identitysandbox.gov environment and is planned to be released in production this 2022-05-12.

**Comment by FuhuXia** [comment]
**SingleLogoutService** release is rolled back on identitysandbox.gov environment and put on hold.

**Comment by FuhuXia** [comment]
reference to https://github.com/GSA/data.gov/issues/3708, since it is related to login.gov not supporting SLO.

**Comment by nickumia-reisys** [comment]
To support the understanding of this ticket...

Since Login.gov does not support SLO and that is the only method that `ckanext-saml2auth` tries to logout with, when a user attempts to logout from CKAN, 
- `ckanext-saml2auth` sends the logout request to login.gov
- Login.gov rejects it and the `ckanext-saml2auth` code fails.
- We wrote a custom fix to ignore the error and just destroy the CKAN cookie that is managing the user session ➡️ https://github.com/keitaroinc/ckanext-saml2auth/pull/72

This is the actual error that we are ignoring
```bash
ckan_1                  | 2023-01-07 15:39:04,961 ERROR [ckanext.saml2auth.plugin] SLO not supported by IDP: None
ckan_1                  | Traceback (most recent call last):
ckan_1                  |   File "/src/ckanext-saml2auth/ckanext/saml2auth/plugin.py", line 133, in _perform_slo
ckan_1                  |     result = client.global_logout(name_id=subject_id)
ckan_1                  |   File "/usr/local/lib/python3.8/site-packages/saml2/client.py", line 210, in global_logout
ckan_1                  |     return self.do_logout(
ckan_1                  |   File "/src/ckanext-saml2auth/ckanext/saml2auth/client.py", line 35, in do_logout
ckan_1                  |     return super().do_logout(*args, **kwargs)
ckan_1                  |   File "/usr/local/lib/python3.8/site-packages/saml2/client.py", line 259, in do_logout
ckan_1                  |     bindings_slo_supported = self.metadata.single_logout_service(
ckan_1                  |   File "/usr/local/lib/python3.8/site-packages/saml2/mdstore.py", line 1236, in single_logout_service
ckan_1                  |     return self.service(entity_id, "%s_descriptor" % typ,
ckan_1                  |   File "/usr/local/lib/python3.8/site-packages/saml2/mdstore.py", line 1147, in service
ckan_1                  |     raise UnsupportedBinding(binding)
ckan_1                  | saml2.s_utils.UnsupportedBinding: None
```

These are the lines of code that try to do the logout: https://github.com/keitaroinc/ckanext-saml2auth/blob/main/ckanext/saml2auth/plugin.py#L129-L136
Since it fails, these are the lines of code that destroy the CKAN user session anyway: https://github.com/keitaroinc/ckanext-saml2auth/blob/main/ckanext/saml2auth/plugin.py#L100-L109
