### ISSUE TITLE
View Full Metadata link not working

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3061]
On a geospatial dataset (ISO metadata), if you click on the `View Full Metadata` link, you get a blank page.
The `Download Metadata` link works normally, so something is wrong with the view (but not the data itself)

## How to reproduce

1. Go to https://catalog.data.gov/dataset/noaa-wds-paleoclimatology-iaea-miba-moisture-isotopes-in-the-biosphere-and-atmosphere
1. Click `View Full Metadata`
1. See blank page

## Expected behavior

Prettified (HTML) view of the ISO metadata

## Actual behavior
Blank page

## Sketch
This has been broken in the past, should review past PR's/tickets for references/code changes.

**Comment by FuhuXia** [comment]
New findings,  For example URL `/dataset/allegheny-county-street-centerlines-201507`

![image](https://user-images.githubusercontent.com/1392461/178504854-6c71d3ba-2001-49d4-8819-3730d623ebcf.png)

On FCS, links 1, 2, 3 are working. 4 gives blank page.
On Cloud.gov, links 1, 3 are working,  2, 4 give `Internal server error` with error message in the log
```
ERR Traceback (most recent call last):
OUT content = util.transform_to_html(content, xslt_package, xslt_path)
ERR File "/home/vcap/deps/1/python/lib/python3.7/site-packages/flask/app.py", line 1499, in full_dispatch_request
ERR rv = self.dispatch_request()
OUT AttributeError: module 'ckanext.spatial.util' has no attribute 'transform_to_html'
ERR File "/home/vcap/deps/1/python/lib/python3.7/site-packages/flask/app.py", line 1485, in dispatch_request
ERR return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
ERR File "/home/vcap/deps/1/python/lib/python3.7/site-packages/newrelic/hooks/framework_flask.py", line 64, in _nr_wrapper_handler_
ERR return wrapped(*args, **kwargs)
ERR File "/home/vcap/deps/1/src/ckanext-spatial/ckanext/spatial/views.py", line 78, in display_html
ERR content = util.transform_to_html(content, xslt_package, xslt_path)
ERR AttributeError: module 'ckanext.spatial.util' has no attribute 'transform_to_html'
```

**Comment by FuhuXia** [comment]
We received high error percentage [New Relic alert](https://radar-api.service.newrelic.com/accounts/1601367/issues/a9f69082-ad4c-4afe-ae7c-63fb404e6545?notifier=SLACK_LEGACY) because of this error.
