### ISSUE TITLE
saml2auth logout generates UnsupportedBinding 500 error

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3544]
After user log into CKAN 2.9 application through login.gov, hitting logout icon will generate a 500 error. User cannot log out.

![Screen Shot 2021-11-17 at 3 59 55 PM](https://user-images.githubusercontent.com/1392461/142282064-5a78eacc-a527-4d32-b72c-485a689e14ce.png)

## How to reproduce

Log into https://catalog-dev-datagov.app.cloud.gov/
Click "Log out" icon.

## Expected behavior

See message 
```
Logged Out
You are now logged out.
```

## Actual behavior

See message 
```
Internal server error
```

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by FuhuXia** [comment]
Error message on the server:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/usr/lib/python3.8/site-packages/ckan/views/user.py", line 487, in logout
    response = item.logout()
  File "/usr/lib/python3.8/site-packages/ckanext/saml2auth/plugin.py", line 100, in logout
    response = _perform_slo()
  File "/usr/lib/python3.8/site-packages/ckanext/saml2auth/plugin.py", line 131, in _perform_slo
    result = client.global_logout(name_id=subject_id)
  File "/usr/lib/python3.8/site-packages/saml2/client.py", line 210, in global_logout
    return self.do_logout(
  File "/usr/lib/python3.8/site-packages/ckanext/saml2auth/client.py", line 35, in do_logout
    return super().do_logout(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/saml2/client.py", line 259, in do_logout
    bindings_slo_supported = self.metadata.single_logout_service(
  File "/usr/lib/python3.8/site-packages/saml2/mdstore.py", line 1236, in single_logout_service
    return self.service(entity_id, "%s_descriptor" % typ,
  File "/usr/lib/python3.8/site-packages/saml2/mdstore.py", line 1147, in service
    raise UnsupportedBinding(binding)
saml2.s_utils.UnsupportedBinding: None
```
