### ISSUE TITLE
SAML2 RequestedAuthnContext AttributeError on CKAN 2.9 when using pysaml2 7.1.0

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3568]
Login button generate 500 error on CKAN 2.9 app when SAML2AUTH is enabled. Error message:
```
Traceback (most recent call last):
  File "/home/vcap/deps/1/python/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vcap/deps/1/python/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vcap/deps/1/python/lib/python3.8/site-packages/ckanext/saml2auth/views/saml2auth.py", line 297, in saml2login
    reqid, info = client.prepare_for_authenticate(requested_authn_context=final_context, relay_state=relay_state)
  File "/home/vcap/deps/1/python/lib/python3.8/site-packages/saml2/client.py", line 72, in prepare_for_authenticate
    reqid, negotiated_binding, info = self.prepare_for_negotiated_authenticate(
  File "/home/vcap/deps/1/python/lib/python3.8/site-packages/saml2/client.py", line 147, in prepare_for_negotiated_authenticate
    reqid, request = self.create_authn_request(
  File "/home/vcap/deps/1/python/lib/python3.8/site-packages/saml2/client_base.py", line 368, in create_authn_request
    requested_authn_context_accrs = requested_authn_context.get(
AttributeError: 'RequestedAuthnContext' object has no attribute 'get'
```

## How to reproduce

https://inventory-dev-datagov.app.cloud.gov/user/saml2login

## Expected behavior

leads to login.gov page

## Actual behavior

`Internal server error` with detailed error message on the backend.

## workaround

It happens when using pysaml2 `7.1.0`. Workaround is to pinning it to `7.0.1` as in PR https://github.com/GSA/inventory-app/pull/384.

**Comment by FuhuXia** [comment]
Not an issue any more.
