### ISSUE TITLE
Inventory resource page gives 500 error

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3598]
Inventory CKAN 2.9 generated 500 error when the resource page is loaded.

## How to reproduce

Create a dataset on Inventory. Upload a resource. Load the resource page.

## Expected behavior

Resource page loads.

## Actual behavior

500 error

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by FuhuXia** [comment]
Error message captured in gunicorn.log: 
```
2021-12-15 17:50:58,009 INFO  [repoze.who] -- repoze.who request started (/dataset/aaa/resource/cfbec8bb-8dad-47b4-ad43-93c50ab8808a) --                                                                                  [80/1796]
2021-12-15 17:50:58,184 ERROR [ckan.config.middleware.flask_app] expected string or bytes-like object
Traceback (most recent call last):
  File "/usr/lib/ckan-new/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan-new/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/ckan-new/lib/python3.6/site-packages/ckan/config/middleware/../../views/resource.py", line 151, in read
    return base.render(template, extra_vars)
  File "/usr/lib/ckan-new/lib/python3.6/site-packages/ckan/lib/base.py", line 151, in render
    return flask_render_template(template_name, **extra_vars)
  File "/usr/lib/ckan-new/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/lib/ckan-new/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/lib/ckan-new/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/lib/ckan-new/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/lib/ckan-new/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/ckan-new/lib/python3.6/site-packages/ckanext/datastore/templates/package/resource_read.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/usr/lib/ckan-new/src/ckanext-usmetadata/ckanext/usmetadata/plugin/../templates/templates_new/package/resource_read.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/usr/lib/ckan-new/lib/python3.6/site-packages/ckan/templates/package/resource_read.html", line 3, in top-level template code
    {% set res = resource %}
  File "/usr/lib/ckan-new/src/ckanext-usmetadata/ckanext/usmetadata/plugin/../templates/templates_new/package/base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/usr/lib/ckan-new/lib/python3.6/site-packages/ckan/templates/package/base.html", line 4, in top-level template code
    {% set dataset_type = dataset_type or pkg.type or 'dataset' %}
  File "/usr/lib/ckan-new/lib/python3.6/site-packages/ckan/templates/page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/lib/ckan-new/src/ckanext-googleanalyticsbasic/ckanext/googleanalyticsbasic/plugin/../templates/templates_new/base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/usr/lib/ckan-new/src/ckanext-usmetadata/ckanext/usmetadata/plugin/../templates/templates_new/base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/usr/lib/ckan-new/lib/python3.6/site-packages/ckan/templates/base.html", line 106, in top-level template code
    {%- block page %}{% endblock -%}
  File "/usr/lib/ckan-new/lib/python3.6/site-packages/ckan/templates/page.html", line 19, in block "page"
    {%- block content %}
  File "/usr/lib/ckan-new/lib/python3.6/site-packages/ckan/templates/page.html", line 22, in block "content"
    {% block main_content %}
  File "/usr/lib/ckan-new/lib/python3.6/site-packages/ckan/templates/page.html", line 74, in block "main_content"
    {% block primary %}
  File "/usr/lib/ckan-new/lib/python3.6/site-packages/ckan/templates/page.html", line 87, in block "primary"
    {% block primary_content %}
  File "/usr/lib/ckan-new/src/ckanext-usmetadata/ckanext/usmetadata/plugin/../templates/templates_new/package/resource_read.html", line 81, in block "primary_content"
    {% block resource_additional_information %}
  File "/usr/lib/ckan-new/src/ckanext-usmetadata/ckanext/usmetadata/plugin/../templates/templates_new/package/resource_read.html", line 131, in block "resource_additional_information"
    <span class="redacted-md">{{ h.usmetadata_filter(value) }}</span>
  File "/usr/lib/ckan-new/src/ckanext-usmetadata/ckanext/usmetadata/plugin/__init__.py", line 77, in usmetadata_filter
    for redact in re.findall(local_helper.REDACTION_STROKE_REGEX, data):
  File "/usr/lib/python3.6/re.py", line 222, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object
2021-12-15 17:50:58,258 ERROR [ckan.lib.webassets_tools] Trying to include unknown asset: <base/vendor/jquery.js>
2021-12-15 17:50:58,259 ERROR [ckan.lib.webassets_tools] Trying to include unknown asset: <base/vendor/jquery.js>
2021-12-15 17:50:58,260 INFO  [ckan.config.middleware.flask_app]  500 /dataset/aaa/resource/cfbec8bb-8dad-47b4-ad43-93c50ab8808a render time 0.251 seconds
```
