### ISSUE TITLE
Inventory data.json export gives 500 instead of capturing errors

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3628]
Data.json export is supposed to capture dataset errors, if any, and save them into `errorlog.txt` inside a zip file. We recently saw it breaks on any error and gives 500 internal server error, no zip file is generated.

## How to reproduce

On your local dev instance, manually create a problematic dataset by adding name/value pair `"parent_dataset": false` into a dataset extra field. Then export the data.json for that organization. 

## Expected behavior

Download a zip file containing `errorlog.txt` with detailed error message.

## Actual behavior

500 internal server error.

Detailed error message in log:
```
2022-01-10 22:15:42,036 ERROR [ckanext.datajson.package2pod] <class 'AttributeError'> : package2pod.py : 162 : 'NoneType' object has no attribute 'extras'
2022-01-10 22:15:42,036 ERROR [ckanext.datajson.package2pod] <class 'AttributeError'> : package2pod.py : 71 : 'NoneType' object has no attribute 'extras'
2022-01-10 22:15:42,037 ERROR [ckanext.datajson.blueprint] <class 'AttributeError'> : blueprint.py : 197 : 'NoneType' object has no attribute 'extras'
2022-01-10 22:15:42,037 ERROR [ckan.config.middleware.flask_app] a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/lib/ckan-new/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan-new/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/ckan-new/src/ckanext-datajson/ckanext/datajson/blueprint.py", line 49, in generate_unredacted
    return generate('unredacted', org_id=org_id)
  File "/usr/lib/ckan-new/src/ckanext-datajson/ckanext/datajson/blueprint.py", line 85, in generate
    resp = Response(make_json(export_type, org_id), mimetype='application/octet-stream')
  File "/usr/lib/ckan-new/src/ckanext-datajson/ckanext/datajson/blueprint.py", line 234, in make_json
    return write_zip(data, error, errors_json, zip_name=export_type)
  File "/usr/lib/ckan-new/src/ckanext-datajson/ckanext/datajson/blueprint.py", line 333, in write_zip
    zf.writestr('errorlog.txt', error.encode('utf8').replace("\n", "\r\n"))
TypeError: a bytes-like object is required, not 'str'
```

## Sketch

Similar to https://github.com/GSA/datagov-deploy/issues/3616.

**Comment by FuhuXia** [comment]
Issue is fixed. Org GSA generated a unredacted.zip with expected content.

![image](https://user-images.githubusercontent.com/1392461/157982337-b4d22df9-1d95-4778-8621-e7d1b8ac9a66.png)
