### ISSUE TITLE
Facet link gives 500 error on Catalog organization page

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3691]
## How to reproduce

Go to any organization page, click any facet link on the left.

Example link:
https://catalog-dev-datagov.app.cloud.gov/organization/gsa?tags=test

## Expected behavior

Page loads with 200 status code.

## Actual behavior

500 error.

Error message logged:
```
2022-02-17 16:20:52,834 INFO  [ckan.lib.helpers] Route name "organization_read" is deprecated and will be removed. Please update calls to use "organization.read" instead
2022-02-17 16:20:52,834 INFO  [ckan.lib.helpers] Route name "organization_about" is deprecated and will be removed. Please update calls to use "organization.about" instead
2022-02-17 16:20:52,836 ERROR [ckan.config.middleware.flask_app] 'werkzeug.local.LocalProxy object' has no attribute 'remove_field'
Traceback (most recent call last):
  File "/usr/lib/ckan36/catalog/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan36/catalog/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/ckan36/lib/catalog/src/ckan/ckan/config/middleware/../../views/group.py", line 453, in read
    extra_vars)
  File "/home/ubuntu/ckan36/lib/catalog/src/ckan/ckan/lib/base.py", line 151, in render
    return flask_render_template(template_name, **extra_vars)
  File "/usr/lib/ckan36/catalog/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,

...

  File "/usr/lib/ckan36/catalog/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/lib/ckan36/catalog/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/lib/ckan36/catalog/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/ckan36/lib/catalog/src/ckan/ckan/templates/snippets/search_form.html", line 56, in top-level template code
    {% block search_facets %}
  File "/home/ubuntu/ckan36/lib/catalog/src/ckan/ckan/templates/snippets/search_form.html", line 69, in block "search_facets"
    <a href="{{ facets.remove_field(field, value) }}" class="remove" title="{{ _('Remove') }}"><i class="fa fa-times"></i></a>
```

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by FuhuXia** [comment]
Duplicate of https://github.com/GSA/datagov-deploy/issues/3672
