### ISSUE TITLE
S3 Output causes logstack-shipper to crash

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#3806]
cloud.gov
https://github.com/GSA/datagov-logstack @ main

## How to reproduce

1. Try to deploy `logstack-shipper` app
    1. `cd datagov-logstack`
    1. `make logstash-installation`
    1. `cf push --vars-file vars.management.yml --strategy rolling`

## Expected behavior

App deploys and does not crash

## Actual behavior

App deploys and crashes with S3 Errors...
```
   2022-05-02T09:31:19.78-0400 [APP/PROC/WEB/0] OUT [2022-05-02T13:31:19,783][WARN ][logstash.outputs.s3      ] Uploading failed, retrying (#391 of Infinity) {:exception=>URI::InvalidURIError, :message=>"bad URI(is not URI?): [@metadata][AWS_S3_PROXY]", :path=>"/home/vcap/tmp/logstash/4b091a42-f089-4954-beea-729ef820eea4/ls.s3.b1874bed-4788-4c70-ba33-495333662068.2022-05-02T13.09.part3.txt", :backtrace=>["uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/uri/rfc3986_parser.rb:67:in `split'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/uri/rfc3986_parser.rb:73:in `parse'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/uri/common.rb:237:in `parse'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/net_http/connection_pool.rb:234:in `pool_options'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/net_http/connection_pool.rb:210:in `for'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/net_http/handler.rb:52:in `pool_for'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/net_http/handler.rb:119:in `session'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/net_http/handler.rb:71:in `transmit'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/net_http/handler.rb:45:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/plugins/content_length.rb:12:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/s3_request_signer.rb:88:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/s3_request_signer.rb:23:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/s3_host_id.rb:14:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/xml/error_handler.rb:8:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/s3_request_signer.rb:65:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/s3_redirects.rb:15:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/retry_errors.rb:108:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/s3_dualstack.rb:32:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/s3_accelerate.rb:49:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/s3_md5s.rb:31:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/s3_expect_100_continue.rb:21:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/s3_bucket_name_restrictions.rb:12:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/rest/handler.rb:7:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/plugins/endpoint.rb:41:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:19:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/s3_dualstack.rb:24:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/s3_accelerate.rb:34:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/plugins/response_target.rb:21:in `call'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/request.rb:70:in `send_request'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/base.rb:207:in `block in define_operation_methods'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/s3/file_uploader.rb:42:in `block in put_object'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/s3/file_uploader.rb:49:in `open_file'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/s3/file_uploader.rb:41:in `put_object'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/s3/file_uploader.rb:34:in `upload'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/s3/object.rb:252:in `upload_file'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/logstash-output-s3-4.3.5/lib/logstash/outputs/s3/uploader.rb:40:in `upload'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/logstash-output-s3-4.3.5/lib/logstash/outputs/s3/uploader.rb:30:in `block in upload_async'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/java_executor_service.rb:79:in `run'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/java_executor_service.rb:24:in `post'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/logstash-output-s3-4.3.5/lib/logstash/outputs/s3/uploader.rb:28:in `upload_async'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/logstash-output-s3-4.3.5/lib/logstash/outputs/s3.rb:368:in `upload_file'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/logstash-output-s3-4.3.5/lib/logstash/outputs/s3.rb:355:in `block in rotate_if_needed'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/logstash-output-s3-4.3.5/lib/logstash/outputs/s3/file_repository.rb:83:in `block in get_factory'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/logstash-output-s3-4.3.5/lib/logstash/outputs/s3/file_repository.rb:26:in `block in with_lock'", "org/jruby/ext/thread/Mutex.java:164:in `synchronize'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/logstash-output-s3-4.3.5/lib/logstash/outputs/s3/file_repository.rb:25:in `with_lock'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/logstash-output-s3-4.3.5/lib/logstash/outputs/s3/file_repository.rb:83:in `get_factory'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/logstash-output-s3-4.3.5/lib/logstash/outputs/s3.rb:346:in `block in rotate_if_needed'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/logstash-output-s3-4.3.5/lib/logstash/outputs/s3.rb:342:in `rotate_if_needed'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/logstash-output-s3-4.3.5/lib/logstash/outputs/s3.rb:327:in `block in start_periodic_check'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'", "com/concurrent_ruby/ext/SynchronizationLibrary.java:232:in `synchronize'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:19:in `execute'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/timer_task.rb:312:in `execute_task'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'", "com/concurrent_ruby/ext/SynchronizationLibrary.java:232:in `synchronize'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:19:in `execute'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/ivar.rb:169:in `safe_execute'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/scheduled_task.rb:285:in `process_task'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/timer_set.rb:165:in `block in process_tasks'", "/home/vcap/app/logstash-7.16.3/vendor/bundle/jruby/2.5.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/java_executor_service.rb:79:in `run'"]}
```

## Sketch

- [x] Investigate and fix the error above.

**Comment by nickumia-reisys** [comment]
The issue was improper setting of the `AWS_S3_PROXY` environment variable in the `.profile`

https://github.com/GSA/datagov-logstack/pull/40/files#diff-94f41f04659846ca294a81d7f791023cf88161dcfb2cc5d3ce1cc0e996a0b474L14-R14
