### ISSUE TITLE
Fix ckanext-harvester send mail

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#3813]
catalog @ smtp-setup
datagov-brokerpak-smtp @ v1.1.3
gsa/ckanext-harvest @ jinja-render2

## How to reproduce

1. Create a datagov-smtp service
2. Bind service to catalog main app
3. Configure CKAN with smtp credentials
4. Perform action that would send email (e.g. harvesting)
5. Wait for email to be generated

## Expected behavior

Email sent to desired recipient

## Actual behavior

```bash
   2022-05-04T16:11:49.31-0400 [APP/TASK/harvester/0] ERR 2022-05-04 20:11:49,311 INFO  [ckan.lib.mailer] Sent email to aaron.borden@gsa.gov
   2022-05-04T16:11:49.49-0400 [APP/TASK/harvester/0] ERR 2022-05-04 20:11:49,499 ERROR [ckanext.harvest.logic.action.update] 'NoneType' object has no attribute 'strip'
   2022-05-04T16:11:49.49-0400 [APP/TASK/harvester/0] ERR Traceback (most recent call last):
   2022-05-04T16:11:49.49-0400 [APP/TASK/harvester/0] ERR File "/home/vcap/deps/1/bin/ckan", line 8, in <module>
   2022-05-04T16:11:49.49-0400 [APP/TASK/harvester/0] ERR sys.exit(ckan())
   2022-05-04T16:11:49.49-0400 [APP/TASK/harvester/0] ERR File "/home/vcap/deps/1/python/lib/python3.7/site-packages/click/core.py", line 829, in __call__
   2022-05-04T16:11:49.49-0400 [APP/TASK/harvester/0] ERR return self.main(*args, **kwargs)
   2022-05-04T16:11:49.49-0400 [APP/TASK/harvester/0] ERR File "/home/vcap/deps/1/python/lib/python3.7/site-packages/click/core.py", line 782, in main
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR rv = self.invoke(ctx)
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR File "/home/vcap/deps/1/python/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR return _process_result(sub_ctx.command.invoke(sub_ctx))
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR File "/home/vcap/deps/1/python/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR return _process_result(sub_ctx.command.invoke(sub_ctx))
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR File "/home/vcap/deps/1/python/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR return ctx.invoke(self.callback, **ctx.params)
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR File "/home/vcap/deps/1/python/lib/python3.7/site-packages/click/core.py", line 610, in invoke
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR return callback(*args, **kwargs)
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR File "/home/vcap/deps/1/python/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR return f(get_current_context(), *args, **kwargs)
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/cli.py", line 264, in run
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR utils.run_harvester()
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/utils.py", line 364, in run_harvester
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR tk.get_action("harvest_jobs_run")(context, {})
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR File "/home/vcap/deps/1/python/lib/python3.7/site-packages/ckan/logic/__init__.py", line 504, in wrapped
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR result = _action(context, data_dict, **kw)
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/logic/action/update.py", line 715, in harvest_jobs_run
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR send_summary_email(context, job_obj.source.id, status)
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/logic/action/update.py", line 810, in send_summary_email
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR send_mail(recipients, subject, body)
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/logic/action/update.py", line 828, in send_mail
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR mailer.mail_recipient(**email)
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR File "/home/vcap/deps/1/python/lib/python3.7/site-packages/ckan/lib/mailer.py", line 125, in mail_recipient
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR body_html=body_html, headers=headers)
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR File "/home/vcap/deps/1/python/lib/python3.7/site-packages/ckan/lib/mailer.py", line 107, in _mail_recipient
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR smtp_connection.sendmail(mail_from, [recipient_email], msg.as_string())
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR File "/home/vcap/deps/1/python/lib/python3.7/smtplib.py", line 877, in sendmail
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR (code, resp) = self.rcpt(each, rcpt_options)
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR File "/home/vcap/deps/1/python/lib/python3.7/smtplib.py", line 547, in rcpt
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR self.putcmd("rcpt", "TO:%s%s" % (quoteaddr(recip), optionlist))
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR File "/home/vcap/deps/1/python/lib/python3.7/smtplib.py", line 153, in quoteaddr
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR if addrstring.strip().startswith('<'):
   2022-05-04T16:11:49.50-0400 [APP/TASK/harvester/0] ERR AttributeError: 'NoneType' object has no attribute 'strip'
   2022-05-04T16:11:49.83-0400 [APP/TASK/harvester/0] OUT Exit status 1
```

## Sketch

- [x] Debug which lines in `ckanext-harvest` or `smtp` or `ckan` or just config is messed up
- [x] Fix code or configuration
- [x] Re-test
- [ ] Merge

**Comment by nickumia-reisys** [comment]
This is the line that generates the list of emails to send to.. https://github.com/GSA/ckanext-harvest/blob/render-jinja2/ckanext/harvest/logic/action/update.py#L809

**Comment by jbrown-xentity** [comment]
Actually, it's extended here: https://github.com/GSA/ckanext-datagovcatalog/blob/main/ckanext/datagovcatalog/harvester/notifications.py#L11

**Comment by nickumia-reisys** [comment]
I tried to replicate the error locally, but it just got stuck here 😕 

![image](https://user-images.githubusercontent.com/85196563/166848301-d271a0ff-25a8-45f1-bf69-fa55c421dcf9.png)

Steps taken:
```bash
1> cd catalog.data.gov
1> make update-dependencies
1> make clean build up                  # Streaming logs
2> cd catalog.data.gov
2> docker-compose exec ckan bash
UI> Create organization, set email, create harvest source, click reharvest
2> ckan harvester run
2> # just hangs..
```

**Comment by nickumia-reisys** [comment]
Okay, I was able to replicate it, local smtp_server needed to explicitly reference port `587`.

It looks like there are some settings in CKAN that are causing some email to be `None`?

```bash
2022-05-05 01:01:29,683 INFO  [ckanext.harvest.logic.action.update] Harvest job run: {}
2022-05-05 01:01:29,712 INFO  [ckanext.harvest.logic.action.create] Harvest job create: {'source_id': 'a506a1c8-2cbe-4c01-9690-581d81c88de7', 'run': True}
2022-05-05 01:01:29,748 WARNI [ckanext.harvest.logic.action.create] There is already an unrun job True for this source a506a1c8-2cbe-4c01-9690-581d81c88de7
2022-05-05 01:01:29,764 INFO  [ckanext.harvest.logic.action.update] Trying to rerun job for a506a1c8-2cbe-4c01-9690-581d81c88de7 skipping
2022-05-05 01:01:29,831 INFO  [ckanext.harvest.logic.action.update] Marking job as finished https://raw.githubusercontent.com/GSA/ckanext-datajson/main/ckanext/datajson/tests/datajson-samples/collection-2-parent-4-children.data.json 14ef9975-4359-4bae-9e86-cd770148bc8c
2022-05-05 01:01:29,895 DEBUG [ckanext.harvest.logic.action.update] Updating search index for harvest source: test
2022-05-05 01:01:30,186 DEBUG [ckanext.harvest.logic.action.update] Notifications: All:True On error:False Errors:0
2022-05-05 01:01:30,237 INFO  [ckan.lib.helpers] Route name "harvest_job_show" is deprecated and will be removed. Please update calls to use "harvester.job_show" instead
2022-05-05 01:01:30,302 INFO  [ckanext.datagovcatalog.harvester.notifications] Adding extra recipients for source a506a1c8-2cbe-4c01-9690-581d81c88de7
2022-05-05 01:01:30,348 INFO  [ckanext.geodatagov.plugins] Added FQ to collection_package_id
2022-05-05 01:01:30,414 INFO  [ckanext.datagovcatalog.harvester.notifications] Extra recipients for source found: [{'name': 'nickumia6@gmail.com', 'email': 'nickumia6@gmail.com'}]
{'recipient_name': 'admin', 'recipient_email': 'your_email@example.com', 'subject': 'CKAN - Harvesting Job Successful - Summary Notification', 'body': 'This is a summary of the latest harvest job set-up in http://ckan:5000.\nJob URL: http://ckan:5000/harvest/a506a1c8-2cbe-4c01-9690-581d81c88de7/job/14ef9975-4359-4bae-9e86-cd770148bc8c\n\nHarvest Source: test\nHarvest Configuration: Not specified\n\nOrganization: smtp\n\nHarvest Job Id: 14ef9975-4359-4bae-9e86-cd770148bc8c\nCreated: 2022-05-05 01:01:24.133665\nFinished: 2022-05-05 01:01:24.844554\n\nRecords in Error: 0\nRecords Added: 0\nRecords Updated: 0\nRecords Deleted: 0\n\nError Summary: 0 errors\nJob Errors: 0\n\n\nDocument Error: 0\n\n\n--\nYou are receiving this email because you are currently set-up as Administrator for http://ckan:5000.\nPlease do not reply to this email as it was sent from a non-monitored address.'}
2022-05-05 01:01:32,646 INFO  [ckan.lib.mailer] Sent email to your_email@example.com
{'recipient_name': 'default', 'recipient_email': None, 'subject': 'CKAN - Harvesting Job Successful - Summary Notification', 'body': 'This is a summary of the latest harvest job set-up in http://ckan:5000.\nJob URL: http://ckan:5000/harvest/a506a1c8-2cbe-4c01-9690-581d81c88de7/job/14ef9975-4359-4bae-9e86-cd770148bc8c\n\nHarvest Source: test\nHarvest Configuration: Not specified\n\nOrganization: smtp\n\nHarvest Job Id: 14ef9975-4359-4bae-9e86-cd770148bc8c\nCreated: 2022-05-05 01:01:24.133665\nFinished: 2022-05-05 01:01:24.844554\n\nRecords in Error: 0\nRecords Added: 0\nRecords Updated: 0\nRecords Deleted: 0\n\nError Summary: 0 errors\nJob Errors: 0\n\n\nDocument Error: 0\n\n\n--\nYou are receiving this email because you are currently set-up as Administrator for http://ckan:5000.\nPlease do not reply to this email as it was sent from a non-monitored address.'}
2022-05-05 01:01:34,839 ERROR [ckanext.harvest.logic.action.update] 'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "/usr/bin/ckan", line 8, in <module>
    sys.exit(ckan())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/srv/app/src/ckanext-harvest/ckanext/harvest/cli.py", line 264, in run
    utils.run_harvester()
  File "/srv/app/src/ckanext-harvest/ckanext/harvest/utils.py", line 364, in run_harvester
    tk.get_action("harvest_jobs_run")(context, {})
  File "/usr/lib/python3.8/site-packages/ckan/logic/__init__.py", line 504, in wrapped
    result = _action(context, data_dict, **kw)
  File "/srv/app/src/ckanext-harvest/ckanext/harvest/logic/action/update.py", line 715, in harvest_jobs_run
    send_summary_email(context, job_obj.source.id, status)
  File "/srv/app/src/ckanext-harvest/ckanext/harvest/logic/action/update.py", line 810, in send_summary_email
    send_mail(recipients, subject, body)
  File "/srv/app/src/ckanext-harvest/ckanext/harvest/logic/action/update.py", line 829, in send_mail
    mailer.mail_recipient(**email)
  File "/usr/lib/python3.8/site-packages/ckan/lib/mailer.py", line 123, in mail_recipient
    return _mail_recipient(recipient_name, recipient_email,
  File "/usr/lib/python3.8/site-packages/ckan/lib/mailer.py", line 107, in _mail_recipient
    smtp_connection.sendmail(mail_from, [recipient_email], msg.as_string())
  File "/usr/lib/python3.8/smtplib.py", line 885, in sendmail
    (code, resp) = self.rcpt(each, rcpt_options)
  File "/usr/lib/python3.8/smtplib.py", line 546, in rcpt
    self.putcmd("rcpt", "TO:%s%s" % (quoteaddr(recip), optionlist))
  File "/usr/lib/python3.8/smtplib.py", line 154, in quoteaddr
    if addrstring.strip().startswith('<'):
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by nickumia-reisys** [comment]
Changing all of the user emails to valid emails made it work...

![image](https://user-images.githubusercontent.com/85196563/166850543-a18f7e94-d563-4cb8-ae36-bbd3775d3016.png)

**Comment by nickumia-reisys** [comment]
On catalog-dev, there is a `datagov_catalog` user with no email so it looks like harvesting emails just error out when it reaches that one and upstream does not handle errors properly...

![image](https://user-images.githubusercontent.com/85196563/166850736-963ee9fc-28bf-4ab4-b4e5-f3f7581a9a76.png)

**Comment by FuhuXia** [comment]
`datagov_catalog` is used as catalog.data.gov's  [site_id](https://github.com/GSA/catalog.data.gov/blob/d3c86a4dd17a8754c5fda8764f3574e86f1ae04d/ckan/setup/ckan.ini#L103) . I think it is added as a user some where in the process when we do db migration from ckan 2.8 to ckan 2.9. We can run the following sql commands to add a dump email address to the db as a workaround.

```
--Verify the record is the one you want to add email to:
select * from "user" where name ='datagov_catalog';
```
Then
```
-- Add email
update "user" set email = 'datagovhelp@localdomain.local' where name ='datagov_catalog';
```

**Comment by nickumia-reisys** [comment]
To summarize,
- `datagov-brokerpak-smtp` can send emails.
- `catalog.data.gov` was deployed to development and verified that it can send emails.
- There is a bug in the upstream code where the `ckan harvester run` command exits immediately if an email for a desired user is not set.
- Fuhu's workaround will mask the bug for our deployment.

**Comment by hkdctol** [comment]
leaving here until we actually switch over to catalog on cloud.gov

**Comment by nickumia-reisys** [comment]
This probably isn't related to this isssue, but I have these commands and I wanted to put them somewhere, so...
```sql
update public.group_extra set value = CONCAT(MD5(value), '@localdomain.local') and key = 'email_list';
update "user" set email = CONCAT(MD5(email), '@localdomain.local') where email not like '%xia%';
update group_extra set value = 'University' where key = 'blahblahblah@localdomain.local';
```
