### ISSUE TITLE
Error with arcgis harvest source

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3845]
Harvesting a Arcgis source generates an error in fetch process. No records can be harvested.

## How to reproduce

Harvest an Arcgis harvest source such as this one
https://catalog-dev-datagov.app.cloud.gov/harvest/admin/bdf13a95-02d1-4f3d-8c5d-f01feef6ae5e

## Expected behavior

Records harvested.

## Actual behavior

Error in fetch.
```
Traceback (most recent call last):
File "/home/vcap/deps/1/bin/ckan", line 8, in <module>
sys.exit(ckan())
File "/home/vcap/deps/1/python/lib/python3.7/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/home/vcap/deps/1/python/lib/python3.7/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/home/vcap/deps/1/python/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/vcap/deps/1/python/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/vcap/deps/1/python/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/vcap/deps/1/python/lib/python3.7/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/cli.py", line 249, in fetch_consumer
utils.fetch_consumer()
File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/utils.py", line 355, in fetch_consumer
fetch_callback(consumer, method, header, body)
File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/queue.py", line 497, in fetch_callback
fetch_and_import_stages(harvester, obj)
File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/queue.py", line 515, in fetch_and_import_stages
success_import = harvester.import_stage(obj)
File "/home/vcap/deps/1/src/ckanext-geodatagov/ckanext/geodatagov/harvesters/arcgis.py", line 275, in import_stage
package_dict = self.make_package_dict(harvest_object, content)
File "/home/vcap/deps/1/src/ckanext-geodatagov/ckanext/geodatagov/harvesters/arcgis.py", line 334, in make_package_dict
name = _slugify(content.get('title') or content.get('item', ''))
File "/home/vcap/deps/1/src/ckanext-geodatagov/ckanext/geodatagov/harvesters/arcgis.py", line 54, in _slugify
value = str(_slugify_strip_re.sub('', value).strip().lower())
TypeError: cannot use a string pattern on a bytes-like object
```

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by nickumia-reisys** [comment]
This looks very suspiciously like PY2 vs. PY3 issue.  Can someone verify if this is resolved?

P.S. By "someone", I mean @FuhuXia haha...

**Comment by nickumia-reisys** [comment]
Okay, looking at NR for the last 2 months, there have been no instances of this message across any catalog servers.  I stand by that this was a PY2-to-PY3 issue, but either we aren't running this source in production or it has been resolved. 

![image](https://github.com/GSA/data.gov/assets/85196563/d91db354-1a08-4f42-afc2-34ef9f9ef5d9)
