### ISSUE TITLE
Catalog fails to harvest subfolders on WAF sources

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3929]
WAF harvester should be able traverse into subfolders. It is not happening on cloud.gov catalog app.

## How to reproduce

1. Description of steps to reproduce the issue.

## Actual behavior

```
ERR Traceback (most recent call last):                                                                                           
ERR File "/home/vcap/deps/1/src/ckanext-spatial/ckanext/spatial/harvesters/waf.py", line 282, in _extract_waf                    
ERR parsed = scrapers[scraper].parseString(content)                                                                              
ERR File "/home/vcap/deps/1/python/lib/python3.7/site-packages/pyparsing/core.py", line 1141, in parse_string                    
ERR raise exc.with_traceback(None)                                                                                               
ERR pyparsing.exceptions.ParseException: <exception str() failed>                                                                
ERR During handling of the above exception, another exception occurred:                                                          
ERR Traceback (most recent call last):                                                                                           
ERR File "/home/vcap/deps/1/src/ckanext-spatial/ckanext/spatial/harvesters/waf.py", line 105, in gather_stage                    
ERR for url, modified_date in _extract_waf(six.text_type(content),source_url,scraper):                                           
ERR File "/home/vcap/deps/1/src/ckanext-spatial/ckanext/spatial/harvesters/waf.py", line 313, in _extract_waf                    
ERR _extract_waf(content, new_url, scraper, results, new_depth)                                                                  
ERR File "/home/vcap/deps/1/src/ckanext-spatial/ckanext/spatial/harvesters/waf.py", line 284, in _extract_waf                    
ERR parsed = scrapers['other'].parseString(content)                                                                              
ERR File "/home/vcap/deps/1/python/lib/python3.7/site-packages/pyparsing/core.py", line 1141, in parse_string                    
ERR raise exc.with_traceback(None)                                                                                               
ERR pyparsing.exceptions.ParseException: <exception str() failed>                                                                
ERR During handling of the above exception, another exception occurred:                                                          
ERR Traceback (most recent call last):                                                                                           
ERR File "/home/vcap/deps/1/bin/ckan", line 8, in <module>                                                                       
ERR sys.exit(ckan())                                                                                                             
ERR File "/home/vcap/deps/1/python/lib/python3.7/site-packages/click/core.py", line 829, in __call__                             
ERR return self.main(*args, **kwargs)                                                                                            
ERR File "/home/vcap/deps/1/python/lib/python3.7/site-packages/click/core.py", line 782, in main                                 
ERR rv = self.invoke(ctx)                                                                                                        
ERR File "/home/vcap/deps/1/python/lib/python3.7/site-packages/click/core.py", line 1259, in invoke                              
ERR return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                      
ERR File "/home/vcap/deps/1/python/lib/python3.7/site-packages/click/core.py", line 1259, in invoke                              
ERR return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                      
ERR File "/home/vcap/deps/1/python/lib/python3.7/site-packages/click/core.py", line 1066, in invoke                              
ERR return ctx.invoke(self.callback, **ctx.params)                                                                               
ERR File "/home/vcap/deps/1/python/lib/python3.7/site-packages/click/core.py", line 610, in invoke                               
ERR return callback(*args, **kwargs)                                                                                             
ERR File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/cli.py", line 241, in gather_consumer                            
ERR utils.gather_consumer()                                                                                                      
ERR File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/utils.py", line 340, in gather_consumer                          
ERR gather_callback(consumer, method, header, body)                                                                              
ERR File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/queue.py", line 374, in gather_callback                          
ERR harvest_object_ids = gather_stage(harvester, job)                                                                            
ERR File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/queue.py", line 432, in gather_stage                             
ERR harvest_object_ids = harvester.gather_stage(job)                                                                             
ERR File "/home/vcap/deps/1/src/ckanext-spatial/ckanext/spatial/harvesters/waf.py", line 108, in gather_stage                    
ERR msg = 'Error extracting URLs from %s, error was %s' % (source_url, e)                                                        
ERR File "/home/vcap/deps/1/python/lib/python3.7/site-packages/pyparsing/exceptions.py", line 149, in __str__                    
ERR found_match = _exception_word_extractor.match(self.pstr, self.loc)                                                           
ERR TypeError: cannot use a string pattern on a bytes-like object                                                                
OUT Exit status 1     
```

## Sketch

- [ ] Build out test case by creating subfolders in the catalog harvesting test case

**Comment by nickumia-reisys** [comment]
This is a bug from the PY3 Upgrade, relating to
- https://github.com/GSA/data.gov/issues/3401
- https://github.com/GSA/ckanext-geodatagov/pull/190
- https://github.com/GSA/datagov-ckan-multi/issues/570
- https://github.com/GSA/ckanext-spatial/pull/11
