### ISSUE TITLE
Dashboard Egress not working

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4041]
```
   2022-11-02T11:08:49.24-0600 [STG/0] ERR [DownloadCache]                  WARN  Unable to download https://java-buildpack.cloudfoundry.org/jvmkill/bionic/x86_64/index.yml into cache /tmp: end of file reached
   2022-11-02T11:08:49.24-0600 [STG/0] ERR [Buildpack]                      ERROR Detect failed with exception #<RuntimeError: Jvmkill Agent error: Unable to find cached file for https://java-buildpack.cloudfoundry.org/jvmkill/bionic/x86_64/index.yml>
   2022-11-02T11:08:49.24-0600 [STG/0] ERR Jvmkill Agent error: Unable to find cached file for https://java-buildpack.cloudfoundry.org/jvmkill/bionic/x86_64/index.yml
   2022-11-02T11:08:49.74-0600 [STG/0] OUT -------> Buildpack version 4.4.66
   2022-11-02T11:08:49.92-0600 [STG/0] OUT WARNING: buildpack version changed from 4.4.65 to 4.4.66
   2022-11-02T11:08:50.56-0600 [STG/0] OUT Installing HTTPD
   2022-11-02T11:08:50.56-0600 [STG/0] OUT HTTPD 2.4.54
   2022-11-02T11:08:50.85-0600 [STG/0] OUT Downloaded [https://buildpacks.cloudfoundry.org/dependencies/httpd/httpd_2.4.54_linux_x64_cflinuxfs3_ebde532e.tgz] to [/tmp]
   2022-11-02T11:08:51.13-0600 [STG/0] OUT Installing PHP
   2022-11-02T11:08:51.13-0600 [STG/0] OUT PHP 7.4.30
   2022-11-02T11:08:53.48-0600 [STG/0] OUT Downloaded [https://buildpacks.cloudfoundry.org/dependencies/php/php_7.4.30_linux_x64_cflinuxfs3_8bf54d2e.tgz] to [/tmp]
   2022-11-02T11:08:53.56-0600 [STG/0] ERR WARNING: php 7.4.x will no longer be available in new buildpacks released after 2022-11-28.
   2022-11-02T11:08:53.56-0600 [STG/0] ERR See: http://php.net/supported-versions.php
   2022-11-02T11:08:56.47-0600 [STG/0] ERR Traceback (most recent call last):
   2022-11-02T11:08:56.47-0600 [STG/0] ERR File "/tmp/buildpacks/1c6562bcca52dc2c6dce78658636177d/scripts/compile.py", line 57, in <module>
   2022-11-02T11:08:56.47-0600 [STG/0] ERR .from_build_pack('lib/additional_commands')
   2022-11-02T11:08:56.47-0600 [STG/0] ERR File "/tmp/buildpacks/1c6562bcca52dc2c6dce78658636177d/lib/build_pack_utils/builder.py", line 212, in extensions
   2022-11-02T11:08:56.47-0600 [STG/0] ERR process_extension(path, ctx, 'compile', process, args=[self])
   2022-11-02T11:08:56.47-0600 [STG/0] ERR File "/tmp/buildpacks/1c6562bcca52dc2c6dce78658636177d/lib/build_pack_utils/utils.py", line 69, in process_extension
   2022-11-02T11:08:56.47-0600 [STG/0] ERR success(getattr(extn, to_call)(*args))
   2022-11-02T11:08:56.47-0600 [STG/0] ERR File "/tmp/buildpacks/1c6562bcca52dc2c6dce78658636177d/extensions/newrelic/extension.py", line 198, in compile
   2022-11-02T11:08:56.47-0600 [STG/0] ERR install.package('NEWRELIC')
   2022-11-02T11:08:56.47-0600 [STG/0] ERR File "/tmp/buildpacks/1c6562bcca52dc2c6dce78658636177d/lib/build_pack_utils/builder.py", line 188, in package
   2022-11-02T11:08:56.47-0600 [STG/0] ERR self._installer.install_binary(key)
   2022-11-02T11:08:56.47-0600 [STG/0] ERR File "/tmp/buildpacks/1c6562bcca52dc2c6dce78658636177d/lib/build_pack_utils/cloudfoundry.py", line 214, in install_binary
   2022-11-02T11:08:56.47-0600 [STG/0] ERR strip=strip)
   2022-11-02T11:08:56.47-0600 [STG/0] ERR File "/tmp/buildpacks/1c6562bcca52dc2c6dce78658636177d/lib/build_pack_utils/cloudfoundry.py", line 190, in _install_binary_from_manifest
   2022-11-02T11:08:56.47-0600 [STG/0] ERR self._dwn.download(url, self._ctx['TMPDIR'])
   2022-11-02T11:08:56.47-0600 [STG/0] ERR File "/tmp/buildpacks/1c6562bcca52dc2c6dce78658636177d/lib/build_pack_utils/downloads.py", line 40, in download
   2022-11-02T11:08:56.47-0600 [STG/0] ERR raise RuntimeError("Checksum of downloaded dependency does not match expected value")
   2022-11-02T11:08:56.47-0600 [STG/0] ERR RuntimeError: Checksum of downloaded dependency does not match expected value
   2022-11-02T11:08:56.48-0600 [STG/0] ERR Failed to compile droplet: Failed to run finalize script: exit status 1
   2022-11-02T11:08:56.49-0600 [STG/0] OUT Exit status 223
   2022-11-02T11:08:56.98-0600 [STG/0] OUT Cell e49592cc-346d-4fd2-b553-bd659bffafef stopping instance c17c5998-8a48-44bf-af4c-fab27afe71ec
   2022-11-02T11:08:56.98-0600 [STG/0] OUT Cell e49592cc-346d-4fd2-b553-bd659bffafef destroying container for instance c17c5998-8a48-44bf-af4c-fab27afe71ec
   2022-11-02T11:08:57.03-0600 [API/1] ERR Failed to stage build: staging failed
```

## How to reproduce

1. Re-implement the `https_proxy` variable in dashboard-stage
2. Run an restage/restart/push command

## Expected behavior

Restart works as expected

## Actual behavior

Restart fails

## Sketch

Not sure

**Comment by hkdctol** [comment]
Closing dashboard issues
