### ISSUE TITLE
ckanext-saml2auth is not Python 3.10-ready

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4057]
## How to reproduce

1. Discovered in https://github.com/GSA/inventory-app/pull/506

## Expected behavior

```bash
Running setup.py install for ckanext-saml2auth: finished with status 'error'
   error: subprocess-exited-with-error
   
   × Running setup.py install for ckanext-saml2auth did not run successfully.
   │ exit code: 1
   ╰─> [51 lines of output]
   /tmp/contents989705857/deps/1/python/lib/python3.10/site-packages/setuptools/dist.py:286: SetuptoolsDeprecationWarning: The namespace_packages parameter is deprecated, consider using implicit namespaces instead (PEP 420).
   warnings.warn(msg, SetuptoolsDeprecationWarning)
   Traceback (most recent call last):
   File "/tmp/contents989705857/deps/1/python/lib/python3.10/site-packages/pytz/lazy.py", line 3, in <module>
   from UserDict import DictMixin
   ModuleNotFoundError: No module named 'UserDict'
   
   During handling of the above exception, another exception occurred:
   
   Traceback (most recent call last):
   File "<string>", line 2, in <module>
   File "<pip-setuptools-caller>", line 34, in <module>
   File "/tmp/pip-install-u7eirezg/ckanext-saml2auth_7419bc369bbe4a63b7856ab64f8223ad/setup.py", line 31, in <module>
   setup(
   File "/tmp/contents989705857/deps/1/python/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
   return distutils.core.setup(**attrs)
   File "/tmp/contents989705857/deps/1/python/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
   _setup_distribution = dist = klass(attrs)
   File "/tmp/contents989705857/deps/1/python/lib/python3.10/site-packages/setuptools/dist.py", line 476, in __init__
   _Distribution.__init__(
   File "/tmp/contents989705857/deps/1/python/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 280, in __init__
   self.finalize_options()
   File "/tmp/contents989705857/deps/1/python/lib/python3.10/site-packages/setuptools/dist.py", line 900, in finalize_options
   ep(self)
   File "/tmp/contents989705857/deps/1/python/lib/python3.10/site-packages/setuptools/dist.py", line 920, in _finalize_setup_keywords
   ep.load()(self, ep.name, value)
   File "/tmp/contents989705857/deps/1/python/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
   module = import_module(match.group('module'))
   File "/tmp/contents989705857/deps/1/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
   return _bootstrap._gcd_import(name[level:], package, level)
   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
   File "/tmp/contents989705857/deps/1/python/lib/python3.10/site-packages/babel/messages/__init__.py", line 12, in <module>
   from babel.messages.catalog import *
   File "/tmp/contents989705857/deps/1/python/lib/python3.10/site-packages/babel/messages/catalog.py", line 24, in <module>
   from babel.dates import format_datetime
   File "/tmp/contents989705857/deps/1/python/lib/python3.10/site-packages/babel/dates.py", line 23, in <module>
   import pytz as _pytz
   File "/tmp/contents989705857/deps/1/python/lib/python3.10/site-packages/pytz/__init__.py", line 32, in <module>
   from pytz.lazy import LazyDict, LazyList, LazySet
   File "/tmp/contents989705857/deps/1/python/lib/python3.10/site-packages/pytz/lazy.py", line 5, in <module>
   from collections import Mapping as DictMixin
   ImportError: cannot import name 'Mapping' from 'collections' (/tmp/contents989705857/deps/1/python/lib/python3.10/collections/__init__.py)
   [end of output]
   
   note: This error originates from a subprocess, and is likely not a problem with pip.
   error: legacy-install-failure
   
   × Encountered error while trying to install package.
   ╰─> ckanext-saml2auth
   
   note: This is an issue with the package mentioned above, not pip.
   hint: See above for output from the failure.
   Running pip install failed. You need to include all dependencies in the vendor directory.
   **ERROR** Could not install vendored pip packages: could not run pip: exit status 1
```

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

Related to:
- https://github.com/GSA/data.gov/issues/3876

**Comment by FuhuXia** [comment]
closing. ckanext-saml2auth passes python 3.10 test.
