### ISSUE TITLE
harvest failure for ArcGIS source type

### ISSUE THREAD

**Issue by Jin-Sun-tts** [GSA/data.gov#4108]
harvest job failed for gisportal.ibwc.gov

## How to reproduce

harvest source:
URL: https://gisportal.ibwc.gov/agsportal/
Source Type: ArcGIS Rest API
Extra Search Criteria: owner:ibwcgis  

## Expected behavior

return valid datasets

## Actual behavior

errors from gather:

   2022-12-06T20:58:53.51-0500 [APP/PROC/WEB/0] OUT 2022-12-07 01:58:53,514 DEBUG [ckanext.harvest.queue] Received harvest job id: 7ccc5d6c-0f66-424b-a55f-14eee39dc9b2
   2022-12-06T20:58:54.67-0500 [APP/PROC/WEB/0] ERR /home/vcap/deps/1/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py:2464: SAWarning: Usage of the 'related attribute set' operation is not currently supported within the execution stage of the flush process. Results may not be consistent.  Consider using alternative event listeners or connection-level operations instead.
   2022-12-06T20:58:54.67-0500 [APP/PROC/WEB/0] ERR util.warn(
   2022-12-06T20:58:54.67-0500 [APP/PROC/WEB/0] ERR /home/vcap/deps/1/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py:2464: SAWarning: Usage of the 'collection append' operation is not currently supported within the execution stage of the flush process. Results may not be consistent.  Consider using alternative event listeners or connection-level operations instead.
   2022-12-06T20:58:54.67-0500 [APP/PROC/WEB/0] ERR util.warn(
   2022-12-06T20:58:54.67-0500 [APP/PROC/WEB/0] ERR /home/vcap/deps/1/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py:2575: SAWarning: Attribute history events accumulated on 1 previously clean instances within inner-flush event handlers have been reset, and will not result in database updates. Consider using set_committed_value() within inner-flush event handlers to avoid this warning.
   2022-12-06T20:58:54.67-0500 [APP/PROC/WEB/0] ERR util.warn(

errors from fetch:

  2022-12-06T20:59:54.84-0500 [APP/PROC/WEB/0] OUT 2022-12-07 01:59:54,841 DEBUG [ckanext.geodatagov.harvesters.arcgis.import] Import stage for harvest object: 337b1dcc-ced8-41c5-af99-db4914c4203d
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/bin/ckan", line 8, in <module>
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR sys.exit(ckan())
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.8/site-packages/click/core.py", line 829, in __call__
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR return self.main(*args, **kwargs)
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.8/site-packages/click/core.py", line 782, in main
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR rv = self.invoke(ctx)
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR return _process_result(sub_ctx.command.invoke(sub_ctx))
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR return _process_result(sub_ctx.command.invoke(sub_ctx))
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR return ctx.invoke(self.callback, **ctx.params)
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.8/site-packages/click/core.py", line 610, in invoke
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR return callback(*args, **kwargs)
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/cli.py", line 249, in fetch_consumer
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR utils.fetch_consumer()
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/utils.py", line 355, in fetch_consumer
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR fetch_callback(consumer, method, header, body)
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/queue.py", line 497, in fetch_callback
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR fetch_and_import_stages(harvester, obj)
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/queue.py", line 515, in fetch_and_import_stages
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR success_import = harvester.import_stage(obj)
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/src/ckanext-geodatagov/ckanext/geodatagov/harvesters/arcgis.py", line 279, in import_stage
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR package_dict = self.make_package_dict(harvest_object, content)
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/src/ckanext-geodatagov/ckanext/geodatagov/harvesters/arcgis.py", line 351, in make_package_dict
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR notes = strip_tags(content.get('description') or '')
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/src/ckanext-geodatagov/ckanext/geodatagov/harvesters/arcgis.py", line 67, in strip_tags
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR s.feed(html)
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.8/html/parser.py", line 111, in feed
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR self.goahead(0)
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.8/html/parser.py", line 139, in goahead
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR if self.convert_charrefs and not self.cdata_elem:
   2022-12-06T20:59:54.85-0500 [APP/PROC/WEB/0] ERR AttributeError: 'MLStripper' object has no attribute 'convert_charrefs'

**Comment by Jin-Sun-tts** [comment]
fixed above error by adding the missing parameters in MLStripper class.  

run the harvest process, got 20 datasets returned back, But it shows 39 datasets from the query https://gisportal.ibwc.gov/agsportal/sharing/search?f=pjson&q=modified:%5B000000000000000000+TO+999999999999999999%5D%20AND%20(owner:ibwcgis)&num=100&start=0 

investigating the root cause for the difference.

**Comment by Jin-Sun-tts** [comment]
According to this list, we only harvest following TYPEs:

TYPES = ['Web Map', 'KML', 'Mobile Application',
         'Web Mapping Application', 'WMS', 'Map Service']

From this URL, we got return 20 datasets:

https://gisportal.ibwc.gov/agsportal/sharing/search?f=pjson&q=modified:%5B000000000000000000+TO+999999999999999999%5D%20AND%20(owner:ibwcgis)%20AND%20(type:%22Web%20Map%22%20OR%20type:%22KML%22%20OR%20type:%22Mobile%20Application%22%20OR%20type:%22Web%20Mapping%20Application%22%20OR%20type:%22WMS%22%20OR%20type:%22Map%20Service%22)&num=100&start=0


"query": "modified:[000000000000000000 TO 999999999999999999] AND (owner:ibwcgis) AND (type:\"Web Map\" OR type:\"KML\" OR type:\"Mobile Application\" OR type:\"Web Mapping Application\" OR type:\"WMS\" OR type:\"Map Service\")",
"total": 20,

So the harvest result is correct amount.

**Comment by Jin-Sun-tts** [comment]
Tested on development, put extra search criteria with "owner:ibwcgis" to get correct datasets. 

![Screen Shot 2022-12-07 at 4 30 12 PM](https://user-images.githubusercontent.com/104456257/206301343-420492ca-9a51-4549-8d84-2ca254a8bd9f.png)

![Screen Shot 2022-12-07 at 4 35 57 PM](https://user-images.githubusercontent.com/104456257/206301796-cd7f6995-399a-4a6d-aa68-b622c9325ca8.png)
