### ISSUE TITLE
Inventory Builds Failing - `pkg_resources.ContextualVersionConflict`

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4306]
inventory-app @ main

## How to reproduce

1. Run `make clean build up` on main branch

## Expected behavior

CKAN starts

## Actual behavior

CKAN doesn't make it past `prerun.py`
```bash
ckan_1                  | 2023-05-08 15:51:55,209 INFO  [ckan.cli] Using configuration file /srv/app/ckan.ini
ckan_1                  | 2023-05-08 15:51:55,209 INFO  [ckan.config.environment] Loading static files from public
solr_1                  | 2023-05-08 15:51:55.453 INFO  (qtp464400749-23) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/select params={q=*:*&rows=1&wt=json} hits=0 status=0 QTime=0
solr_1                  | 2023-05-08 15:51:55.460 INFO  (qtp464400749-26) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/schema params={wt=schema.xml} status=0 QTime=1
ckan_1                  | 2023-05-08 15:51:55,470 INFO  [ckan.config.environment] Loading templates from /usr/lib/python3.8/site-packages/ckan/templates
ckan_1                  | Traceback (most recent call last):
ckan_1                  |   File "/usr/bin/ckan", line 8, in <module>
ckan_1                  |     sys.exit(ckan())
ckan_1                  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
ckan_1                  |     return self.main(*args, **kwargs)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1054, in main
ckan_1                  |     with self.make_context(prog_name, args, **extra) as ctx:
ckan_1                  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 920, in make_context
ckan_1                  |     self.parse_args(ctx, args)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/cli/cli.py", line 116, in parse_args
ckan_1                  |     result = super(ExtendableGroup, self).parse_args(ctx, args)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1613, in parse_args
ckan_1                  |     rest = super().parse_args(ctx, args)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1378, in parse_args
ckan_1                  |     value, args = param.handle_parse_result(ctx, opts, args)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 2360, in handle_parse_result
ckan_1                  |     value = self.process_value(ctx, value)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 2322, in process_value
ckan_1                  |     value = self.callback(ctx, self, value)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/cli/cli.py", line 126, in _init_ckan_config
ckan_1                  |     _add_ctx_object(ctx, value)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/cli/cli.py", line 135, in _add_ctx_object
ckan_1                  |     ctx.obj = CtxObject(path)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/cli/cli.py", line 57, in __init__
ckan_1                  |     self.app = make_app(self.config)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/config/middleware/__init__.py", line 56, in make_app
ckan_1                  |     load_environment(conf)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/config/environment.py", line 123, in load_environment
ckan_1                  |     p.load_all()
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/plugins/core.py", line 165, in load_all
ckan_1                  |     load(*plugins)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/plugins/core.py", line 179, in load
ckan_1                  |     service = _get_service(plugin)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/plugins/core.py", line 281, in _get_service
ckan_1                  |     return plugin.load()(name=plugin_name)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2470, in load
ckan_1                  |     self.require(*args, **kwargs)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2493, in require
ckan_1                  |     items = working_set.resolve(reqs, env, installer, extras=self.extras)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 800, in resolve
ckan_1                  |     raise VersionConflict(dist, req).with_context(dependent_req)
ckan_1                  | pkg_resources.ContextualVersionConflict: (urllib3 2.0.2 (/usr/lib/python3.8/site-packages), Requirement.parse('urllib3<1.27,>=1.25.4'), {'botocore'})
solr_1                  | 2023-05-08 15:51:55.912 INFO  (qtp464400749-25) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/select params={q=*&wt=json} hits=0 status=0 QTime=0
ckan_1                  | 2023-05-08 15:51:57,561 INFO  [ckan.cli] Using configuration file /srv/app/ckan.ini
ckan_1                  | 2023-05-08 15:51:57,561 INFO  [ckan.config.environment] Loading static files from public
solr_1                  | 2023-05-08 15:51:57.788 INFO  (qtp464400749-20) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/select params={q=*:*&rows=1&wt=json} hits=0 status=0 QTime=0
solr_1                  | 2023-05-08 15:51:57.795 INFO  (qtp464400749-23) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/schema params={wt=schema.xml} status=0 QTime=0
ckan_1                  | 2023-05-08 15:51:57,806 INFO  [ckan.config.environment] Loading templates from /usr/lib/python3.8/site-packages/ckan/templates
ckan_1                  | Traceback (most recent call last):
ckan_1                  |   File "/usr/bin/ckan", line 8, in <module>
ckan_1                  |     sys.exit(ckan())
ckan_1                  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
ckan_1                  |     return self.main(*args, **kwargs)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1054, in main
ckan_1                  |     with self.make_context(prog_name, args, **extra) as ctx:
ckan_1                  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 920, in make_context
ckan_1                  |     self.parse_args(ctx, args)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/cli/cli.py", line 116, in parse_args
ckan_1                  |     result = super(ExtendableGroup, self).parse_args(ctx, args)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1613, in parse_args
ckan_1                  |     rest = super().parse_args(ctx, args)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1378, in parse_args
ckan_1                  |     value, args = param.handle_parse_result(ctx, opts, args)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 2360, in handle_parse_result
ckan_1                  |     value = self.process_value(ctx, value)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/click/core.py", line 2322, in process_value
ckan_1                  |     value = self.callback(ctx, self, value)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/cli/cli.py", line 126, in _init_ckan_config
ckan_1                  |     _add_ctx_object(ctx, value)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/cli/cli.py", line 135, in _add_ctx_object
ckan_1                  |     ctx.obj = CtxObject(path)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/cli/cli.py", line 57, in __init__
ckan_1                  |     self.app = make_app(self.config)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/config/middleware/__init__.py", line 56, in make_app
ckan_1                  |     load_environment(conf)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/config/environment.py", line 123, in load_environment
ckan_1                  |     p.load_all()
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/plugins/core.py", line 165, in load_all
ckan_1                  |     load(*plugins)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/plugins/core.py", line 179, in load
ckan_1                  |     service = _get_service(plugin)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/ckan/plugins/core.py", line 281, in _get_service
ckan_1                  |     return plugin.load()(name=plugin_name)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2470, in load
ckan_1                  |     self.require(*args, **kwargs)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2493, in require
ckan_1                  |     items = working_set.resolve(reqs, env, installer, extras=self.extras)
ckan_1                  |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 800, in resolve
ckan_1                  |     raise VersionConflict(dist, req).with_context(dependent_req)
ckan_1                  | pkg_resources.ContextualVersionConflict: (urllib3 2.0.2 (/usr/lib/python3.8/site-packages), Requirement.parse('urllib3<1.27,>=1.25.4'), {'botocore'})
ckan_1                  | [prerun] Initializing or upgrading db - start
ckan_1                  | [prerun] Initializing or upgrading db - end
ckan_1                  | [prerun] Setting the following plugins in /srv/app/ckan.ini:
ckan_1                  | datagov_inventory datastore xloader stats text_view recline_view googleanalyticsbasic s3filestore dcat_usmetadata usmetadata datajson envvars
ckan_1                  | [prerun] Plugins set.
ckan_1                  | [prerun] Initializing datastore db - start
ckan_1                  | [prerun] Could not initialize datastore
ckan_1                  | can't execute an empty query
ckan_1                  | Traceback (most recent call last):
ckan_1                  |   File "/srv/app/GSA_prerun.py", line 57, in <module>
ckan_1                  |     pr.create_sysadmin()
ckan_1                  |   File "/srv/app/prerun.py", line 162, in create_sysadmin
ckan_1                  |     out = subprocess.check_output(command)
ckan_1                  |   File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
ckan_1                  |     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
ckan_1                  |   File "/usr/lib/python3.8/subprocess.py", line 516, in run
ckan_1                  |     raise CalledProcessError(retcode, process.args,
ckan_1                  | subprocess.CalledProcessError: Command '['ckan', '-c', '/srv/app/ckan.ini', 'user', 'show', 'admin']' returned non-zero exit status 1.
inventory-app_ckan_1 exited with code 1
```

## Sketch

It seems like something changed in python or urllib3 where the native global version `urllib3 2.0.2` differs from the CKAN/BOTO-supported `urllib3 1.26.x`.  From reading online resources, this isn't a python/pip specific issue, the scope of libraries relates to other languages and applications as well.  Essentially, there are two different programs using two different version of the `urllib3` library.  The two programs are sharing some object/memory that is confused since the two programs calling the memory are using conflicting versions of `urllib3`.  As suspected `urllib3 2.0.2` was recently just [5 days ago](https://github.com/urllib3/urllib3/releases/tag/2.0.2).  I don't know how the OFKN image is pulling the latest version of it (since it was built months ago)... Although as I write this, we do install other packages which might cause a system-wide upgrade `RUN apk add vim zip`.  There is definitely an older version of the image we can pin to, in order to get our PRs unblocked.. But it would not be a long term solution.

Tentative sketch:
- [ ] Investigate what changed in `urllib3` and how it relates to Python 3.8 `pkg_resources.ContextualVersionConflict`
- [ ] Fix problem by some means...

**Comment by nickumia-reisys** [comment]
Upon inspection, after our docker build process installs our pip requirements, somehow there are two version of `urllib3` installed.  
![image](https://github.com/GSA/data.gov/assets/85196563/b9c7cfa0-cbd4-4a48-9bed-1a92492cfced)

This should be "impossible" since installing a new version should automatically remove the old version.
![image](https://github.com/GSA/data.gov/assets/85196563/dd94aa4c-2b86-4f7e-a9fa-fdddb0a7556b)

After uninstalling one of the versions, pip does the correct thing to uninstall the existing version and install the new version.
![image](https://github.com/GSA/data.gov/assets/85196563/81bfc506-9d6d-40aa-9c00-d90f673bd0e4)
![image](https://github.com/GSA/data.gov/assets/85196563/b1e1aab1-e0ae-4350-bc69-9c50bb13cedc)

## Current solution

The current solution still has two versions of the library installed.  The only difference is that they are not conflicting (i.e. `urllib3 2.0.0 conflicts with urllib3 1.26.5` BUT `urllib3 1.26.5 does not conflict with urllib3 1.26.6`.  Without doing a completely custom solution to uninstall all version of urllib3 as a separate step in the `dockerfile`, I'm not sure there is a good way of fixing this issue.  I think the co-existing compatible versions work fine for now.

**Comment by nickumia-reisys** [comment]
This was merged on 5/10 with
- https://github.com/GSA/inventory-app/pull/601
