### ISSUE TITLE
CKAN 2.10 - Catalog Clicking on Resource is Broken

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4370]
## How to reproduce

1. Look at tests on catalog `ckan-210` branch

## Expected behavior

Resource page loads

## Actual behavior

Template issue..
![image](https://github.com/GSA/data.gov/assets/85196563/685d498f-e84b-4bec-86a4-99598e4f5ffe)

## Sketch

- [ ] Investigate template that's causing issues.

**Comment by nickumia-reisys** [comment]
The issue is that the `resource_preview` function was removed from CKAN 2.10
- https://github.com/ckan/ckan/compare/ckan-2.9.9...ckan-2.10.0#diff-e37df3cabf7b9e56825183a8bd3dabf6ae2f52c7ca0155860151c69f8cd94f68L2378-L2405

Just for reference, there are more than 3000 commits between `2.9.9` and `2.10.0`.. I was trying to look at the history of the [`ckan.lib.helpers`](https://github.com/ckan/ckan/blob/ckan-2.9.9/ckan/lib/helpers.py) file to see why they deleted it, but couldn't get anything... 
![image](https://github.com/GSA/data.gov/assets/85196563/e2f3d490-af08-409a-940a-fa24fad25341)

Nothing in the migration docs about `resource_preview` changing.. but I'll keep searching

<details closed>
<summary>Full backtrace</summary>
<br>

```bash
ckan_1                  | Traceback (most recent call last):
ckan_1                  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
ckan_1                  |     response = self.handle_exception(e)
ckan_1                  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
ckan_1                  |     response = self.full_dispatch_request()
ckan_1                  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
ckan_1                  |     rv = self.handle_user_exception(e)
ckan_1                  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
ckan_1                  |     rv = self.dispatch_request()
ckan_1                  |   File "/usr/local/lib/python3.8/site-packages/flask_debugtoolbar/__init__.py", line 142, in dispatch_request
ckan_1                  |     return view_func(**req.view_args)
ckan_1                  |   File "/usr/local/lib/python3.8/site-packages/ckan/views/resource.py", line 144, in read
ckan_1                  |     return base.render(template, extra_vars)
ckan_1                  |   File "/usr/local/lib/python3.8/site-packages/ckan/lib/base.py", line 107, in render
ckan_1                  |     return flask_render_template(template_name, **extra_vars)
ckan_1                  |   File "/usr/local/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
ckan_1                  |     return _render(
ckan_1                  |   File "/usr/local/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
ckan_1                  |     rv = template.render(context)
ckan_1                  |   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
ckan_1                  |     self.environment.handle_exception()
ckan_1                  |   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
ckan_1                  |     raise rewrite_traceback_stack(source=source)
ckan_1                  |   File "/src/ckanext-datagovtheme/ckanext/datagovtheme/templates/package/resource_read.html", line 46, in top-level template code
ckan_1                  |     {% set pkg = c.pkg_dict %}
ckan_1                  |   File "/usr/local/lib/python3.8/site-packages/ckan/templates/package/resource_read.html", line 3, in top-level template code
ckan_1                  |     {% set res = resource %}
ckan_1                  |   File "/src/ckanext-datagovtheme/ckanext/datagovtheme/templates/package/base.html", line 3, in top-level template code
ckan_1                  |     {% set pkg = c.pkg_dict %}
ckan_1                  |   File "/src/ckanext-datagovtheme/ckanext/datagovtheme/templates/page.html", line 1, in top-level template code
ckan_1                  |     {% ckan_extends %} {% block maintag %}
ckan_1                  |   File "/usr/local/lib/python3.8/site-packages/ckan/templates/page.html", line 1, in top-level template code
ckan_1                  |     {% extends "base.html" %}
ckan_1                  |   File "/src/ckanext-datagovtheme/ckanext/datagovtheme/templates/base.html", line 1, in top-level template code
ckan_1                  |     {% ckan_extends %}
ckan_1                  |   File "/src/ckanext-harvest/ckanext/harvest/templates/base.html", line 1, in top-level template code
ckan_1                  |     {% ckan_extends %}
ckan_1                  |   File "/src/ckanext-googleanalyticsbasic/ckanext/googleanalyticsbasic/templates/base.html", line 1, in top-level template code
ckan_1                  |     {% ckan_extends %}
ckan_1                  |   File "/usr/local/lib/python3.8/site-packages/ckan/templates/base.html", line 108, in top-level template code
ckan_1                  |     {%- block page %}{% endblock -%}
ckan_1                  |   File "/usr/local/lib/python3.8/site-packages/ckan/templates/page.html", line 19, in block 'page'
ckan_1                  |     {%- block content %}
ckan_1                  |   File "/usr/local/lib/python3.8/site-packages/ckan/templates/page.html", line 22, in block 'content'
ckan_1                  |     {% block main_content %}
ckan_1                  |   File "/usr/local/lib/python3.8/site-packages/ckan/templates/page.html", line 53, in block 'main_content'
ckan_1                  |     {% block pre_primary %}
ckan_1                  |   File "/usr/local/lib/python3.8/site-packages/ckan/templates/package/resource_read.html", line 22, in block 'pre_primary'
ckan_1                  |     {% block resource %}
ckan_1                  |   File "/usr/local/lib/python3.8/site-packages/ckan/templates/package/resource_read.html", line 24, in block 'resource'
ckan_1                  |     {% block resource_inner %}
ckan_1                  |   File "/usr/local/lib/python3.8/site-packages/ckan/templates/package/resource_read.html", line 101, in block 'resource_inner'
ckan_1                  |     {% block data_preview %}
ckan_1                  |   File "/src/ckanext-datagovtheme/ckanext/datagovtheme/templates/package/resource_read.html", line 42, in block 'data_preview'
ckan_1                  |     {{ h.resource_preview_custom(c.resource, c.package.id) or "" }}
ckan_1                  |   File "/src/ckanext-datagovtheme/ckanext/datagovtheme/helpers.py", line 566, in resource_preview_custom
ckan_1                  |     return h.resource_preview(resource, pkg_id)
ckan_1                  | AttributeError: module 'ckan.lib.helpers' has no attribute 'resource_preview'
```
</details>

**Comment by nickumia-reisys** [comment]
Removing the custom function call fixed the issue.
