### ISSUE TITLE
jinja2.exceptions package_count error in catalog-web log review

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4530]
During the recent NewRelic log review, more than 50% of **catalog-web** errors is this

```
File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/templates/snippets/organization.html", line 52, in block 'inner'
{% block nums %}
File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/templates/snippets/organization.html", line 60, in block 'nums'
<dd>{{ h.SI_number_span(organization.package_count) }}</dd>
File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/lib/helpers.py", line 2391, in SI_number_span
number = int(number)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'package_count'
```

## Sketch

Either fix it, or update the NR rule to ignore it.

**Comment by btylerburton** [comment]
To reproduce, add a `?q="` to the end of a query within an organization, such as:

`https://catalog.data.gov/organization/gsa-gov?q=%22`

This does not affect dataset queries such as:

`https://catalog.data.gov/dataset?q=%22`

At the moment, we're trying to determine if this affects a vanilla CKAN install of 2.10.5.

If yes, we will pursue filing a bug with upstream as this would be a core problem.

If no, then we will attempt to patch this in our own code. 

Note that querying SOLR directly with a single double quote will also cause the error `"`

**Comment by btylerburton** [comment]
The error from the SOLR query:

```

  "responseHeader":{
    "status":400,
    "QTime":0,
    "params":{
      "q":"\"",
      "indent":"true",
      "q.op":"OR",
      "_":"1733177831707"}},
  "error":{
    "metadata":[
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","org.apache.solr.parser.TokenMgrError"],
    "msg":"org.apache.solr.search.SyntaxError: Cannot parse '\"': Lexical error at line 1, column 2.  Encountered: <EOF> after : \"\"",
    "code":400}}
```

**Comment by FuhuXia** [comment]
Confirmed a vanilla CKAN 2.10.5. also has this issue.

**Comment by btylerburton** [comment]
> Confirmed a vanilla CKAN 2.10.5. also has this issue.

Given the above, I propose we punt on this issue and start focusing on getting us onto 2.11 which @FuhuXia has tested and confirmed it doesn't have this issue.

Also, since it's a core bug I will post an issue to ckan and see where that leads.

**Comment by FuhuXia** [comment]
We can set some rules in the NewRelic to ignore this kind of messages from the weekly review.

**Comment by btylerburton** [comment]
CKAN issue logged here: https://github.com/ckan/ckan/issues/8562

**Comment by btylerburton** [comment]
> We can set some rules in the NewRelic to ignore this kind of messages from the weekly review.

I'm not so sure. A single instance of this error writes 147 logs to NR...

<img width="1514" alt="Screenshot 2024-12-03 at 11 12 43 AM" src="https://github.com/user-attachments/assets/414f3cef-3657-4efd-8aef-9c090e99f975">

**Comment by btylerburton** [comment]
Blocked by https://github.com/GSA/data.gov/issues/4860

**Comment by FuhuXia** [comment]
`/organization/<org-name>?q=%22` still generate solr error on ckan 2.11.0.
This does not affect user experience.

**Comment by btylerburton** [comment]
Yeah I think we just wanted the error not to bubble up to the UI. 

Error stacktrace for posterity:

```
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] OUT ValueError: not enough values to unpack (expected 2, got 1)
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR 2025-03-25 15:40:26,950 ERROR [ckan.config.middleware.flask_app] Request finalizing failed with an error while handling an error NR-LINKING|***|catalog-admin-prod|
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR response = self.full_dispatch_request()
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/flask/app.py", line 883, in full_dispatch_request
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR return self.finalize_request(rv)
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/flask/app.py", line 904, in finalize_request
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR response = self.process_response(response)
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/newrelic/api/function_trace.py", line 157, in literal_wrapper
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR return wrapped(*args, **kwargs)
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/flask/app.py", line 1281, in process_response
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR response = self.ensure_sync(func)(response)
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/newrelic/api/function_trace.py", line 157, in literal_wrapper
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR return wrapped(*args, **kwargs)
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/ckanext/tracking/middleware.py", line 42, in track_request
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR with cast(sa.engine.Engine, engine).begin() as conn:
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR AttributeError: 'NoneType' object has no attribute 'begin'
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR During handling of the above exception, another exception occurred:
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/flask/app.py", line 904, in finalize_request
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR response = self.process_response(response)
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/newrelic/api/function_trace.py", line 157, in literal_wrapper
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR return wrapped(*args, **kwargs)
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/flask/app.py", line 1281, in process_response
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR response = self.ensure_sync(func)(response)
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/newrelic/api/function_trace.py", line 157, in literal_wrapper
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR return wrapped(*args, **kwargs)
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/ckanext/tracking/middleware.py", line 22, in track_request
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR k, v = part.split('=')
   2025-03-25T10:40:26.95-0500 [APP/PROC/WEB/0] ERR ValueError: not enough values to unpack (expected 2, got 1)
```
