### ISSUE TITLE
Disable CKAN tracking

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#488]
I'm seeing this error in the logs on catalog-web2d:
```
[Thu Nov 15 01:26:23.586763 2018] [:error] [pid 1789:tid 139755571001088] [remote 10.177.19.22:21095] mod_wsgi (pid=1789): Exception occurred processing WSGI script '/etc/ckan/apache.wsgi'.
[Thu Nov 15 01:26:23.586901 2018] [:error] [pid 1789:tid 139755571001088] [remote 10.177.19.22:21095] Traceback (most recent call last):
[Thu Nov 15 01:26:23.586934 2018] [:error] [pid 1789:tid 139755571001088] [remote 10.177.19.22:21095]   File "/usr/lib/ckan-new/src/ckan/ckan/config/middleware.py", line 360, in __call__
[Thu Nov 15 01:26:23.586977 2018] [:error] [pid 1789:tid 139755571001088] [remote 10.177.19.22:21095]     self.engine.execute(sql, key, data.get('url'), data.get('type'))
[Thu Nov 15 01:26:23.586993 2018] [:error] [pid 1789:tid 139755571001088] [remote 10.177.19.22:21095]   File "/usr/lib/ckan/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1690, in execute
[Thu Nov 15 01:26:23.587020 2018] [:error] [pid 1789:tid 139755571001088] [remote 10.177.19.22:21095]     return connection.execute(statement, *multiparams, **params)
[Thu Nov 15 01:26:23.587032 2018] [:error] [pid 1789:tid 139755571001088] [remote 10.177.19.22:21095]   File "/usr/lib/ckan/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 719, in execute
[Thu Nov 15 01:26:23.587049 2018] [:error] [pid 1789:tid 139755571001088] [remote 10.177.19.22:21095]     return self._execute_text(object, multiparams, params)
[Thu Nov 15 01:26:23.587061 2018] [:error] [pid 1789:tid 139755571001088] [remote 10.177.19.22:21095]   File "/usr/lib/ckan/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 868, in _execute_text
[Thu Nov 15 01:26:23.587077 2018] [:error] [pid 1789:tid 139755571001088] [remote 10.177.19.22:21095]     statement, parameters
[Thu Nov 15 01:26:23.587097 2018] [:error] [pid 1789:tid 139755571001088] [remote 10.177.19.22:21095]   File "/usr/lib/ckan/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 954, in _execute_context
[Thu Nov 15 01:26:23.587125 2018] [:error] [pid 1789:tid 139755571001088] [remote 10.177.19.22:21095]     context)
[Thu Nov 15 01:26:23.587137 2018] [:error] [pid 1789:tid 139755571001088] [remote 10.177.19.22:21095]   File "/usr/lib/ckan/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1116, in _handle_dbapi_exception
[Thu Nov 15 01:26:23.587158 2018] [:error] [pid 1789:tid 139755571001088] [remote 10.177.19.22:21095]     exc_info
[Thu Nov 15 01:26:23.587170 2018] [:error] [pid 1789:tid 139755571001088] [remote 10.177.19.22:21095]   File "/usr/lib/ckan/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
[Thu Nov 15 01:26:23.587187 2018] [:error] [pid 1789:tid 139755571001088] [remote 10.177.19.22:21095]     reraise(type(exception), exception, tb=exc_tb)
[Thu Nov 15 01:26:23.587197 2018] [:error] [pid 1789:tid 139755571001088] [remote 10.177.19.22:21095]   File "/usr/lib/ckan/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 947, in _execute_context
[Thu Nov 15 01:26:23.587212 2018] [:error] [pid 1789:tid 139755571001088] [remote 10.177.19.22:21095]     context)
[Thu Nov 15 01:26:23.587223 2018] [:error] [pid 1789:tid 139755571001088] [remote 10.177.19.22:21095]   File "/usr/lib/ckan/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 435, in do_execute
[Thu Nov 15 01:26:23.587255 2018] [:error] [pid 1789:tid 139755571001088] [remote 10.177.19.22:21095]     cursor.execute(statement, parameters)
[Thu Nov 15 01:26:23.587312 2018] [:error] [pid 1789:tid 139755571001088] [remote 10.177.19.22:21095] InternalError: (InternalError) cannot execute INSERT in a read-only transaction
[Thu Nov 15 01:26:23.587343 2018] [:error] [pid 1789:tid 139755571001088] [remote 10.177.19.22:21095]  'INSERT INTO tracking_raw\\n                     (user_key, url, tracking_type)\\n                     VALUES (%s, %s, %s)' ('e14ece75ae299a888beec84df6949b84770e4aef', u'/dataset', u'page')
```

catalog-web2d is talking to a read-only instance, which is expected.

This issue is similar https://github.com/GSA/datagov-deploy/issues/205

**Comment by adborden** [comment]
~Blocks [the release](https://github.com/GSA/datagov-deploy/issues/473) as it renders catalog unusable.~
<img width="986" alt="screen shot 2018-11-14 at 5 31 16 pm" src="https://user-images.githubusercontent.com/509703/48523944-34b42f00-e833-11e8-9192-702d9d10b638.png">

**Comment by adborden** [comment]
We should be able to [disable tracking in config](https://github.com/GSA/datagov-deploy/blob/master/ansible/roles/software/catalog/ckan-app/templates/etc/ckan/production.ini.j2#L203). Is this expected @JJediny ?

**Comment by adborden** [comment]
This isn't a blocker, the 500 was unrelated.

**Comment by adborden** [comment]
Just found the [fix-ckan-tracking role](https://github.com/GSA/datagov-deploy/blob/ea421585b0988aeb6c5207e32db17d7c33729098/ansible/roles/software/ckan/fix-ckan-tracking/tasks/main.yml) that copies some tarball'd JS to update the tracking URL to admin (which has write access). We should remove this role as part of this story.

**Comment by adborden** [comment]
Closing this as the work has been done to disable tracking. https://github.com/GSA/datagov-deploy/issues/1478 should be to track the underlying issues with tracking.

**Comment by nickumia-reisys** [comment]
CKAN Tracking is working on our current system and has no known issues.  We have a github action scheduled job that updates this daily
- https://github.com/GSA/data.gov/issues/1479
