### ISSUE TITLE
CA certificate path is misconfigured for python virtualenv

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#493]
The virtualenv is configured with the wrong CA certificate path so some SSL verifications fail because the root certificates don't exist in the chain.

For example, running the harvester for meta.geo.census.gov, results in an SSL error:
```
WafHarvester gather_stage for job: <H                                                                                                     arvestJob id=5e5b2343-cb70-4b47-9e02-e6a9431227c6 created=2018-11-16 16:09:04.637895 gather_started=2018-11-16                                                                                                      16:09:08.865867 gather_finished=None finished=None source_id=59e385d3-a491-461f-9553-1f23ab7f56f2 status=Runnin                                                                                                     g>
2018-11-16 16:09:08,866 DEBUG [ckanext.spatial.harvesters.base] Using config: {u'validator_profiles': [u'iso191                                                                                                     39ngdc'], u'private_datasets': False}
2018-11-16 16:09:08,881 INFO  [requests.packages.urllib3.connectionpool] Starting new HTTPS connection (1): met                                                                                                     a.geo.census.gov
2018-11-16 16:09:08,949 ERROR [ckanext.harvest.harvesters.base] Unable to get content for URL: https://meta.geo                                                                                                     .census.gov/data/existing/decennial/GEO/GPMB/TIGERline/TL2018/anrc/: SSLError(SSLError(SSLError(1, u'[SSL: CERT                                                                                                     IFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),),)
```

**How to reproduce**
Run this on harvester:

    $ sudo /usr/lib/ckan/bin/python -c "import requests; requests.get('https://meta.geo.census.gov', verify=True); print 'ok'"

**Actual behavior**
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/ckan/lib/python2.7/site-packages/requests/api.py", line 68, in get
    return request('get', url, **kwargs)
  File "/usr/lib/ckan/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/ckan/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/ckan/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/ckan/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

**Expected behavior**

    ok

**Comment by adborden** [comment]
Even though the global DigiCert root certificates exist in `/etc/ssl/certs` you can see the default paths are not looking there:

```
$ sudo /usr/lib/ckan/bin/python -c "import ssl; print(ssl.get_default_verify_paths())"
DefaultVerifyPaths(cafile=None, capath='/usr/lib/ssl/certs', openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/usr/lib/ssl/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/usr/lib/ssl/certs')
```

Setting `SSL_CERT_DIR` works here:
```
$ sudo SSL_CERT_DIR=/etc/ssl/certs /usr/lib/ckan/bin/python -c "import ssl; print(ssl.get_default_verify_paths())"
DefaultVerifyPaths(cafile=None, capath='/etc/ssl/certs', openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/usr/lib/ssl/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/usr/lib/ssl/certs')
```

But not here:
```
$ sudo SSL_CERT_DIR=/etc/ssl/certs /usr/lib/ckan/bin/python -c "import requests; requests.get('https://meta.geo.census.gov', verify=True); print 'ok'"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/ckan/lib/python2.7/site-packages/requests/api.py", line 68, in get
    return request('get', url, **kwargs)
  File "/usr/lib/ckan/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/ckan/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/ckan/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/ckan/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

**Comment by adborden** [comment]
`requests` uses [certifi](http://docs.python-requests.org/en/master/user/advanced/#ca-certificates) for the CA bundle. I don't see a way to configure it, since it's kind of meant to be a curated list of CA certificates.

**Comment by adborden** [comment]
... but we're on requests==1.1.0 which does not support certifi yet, it bundles the certs within requests.

I'm thinking as a quick fix, we'll install certifi and then copy the bundle and overwrite requests version. In the long term, we'll see if we can upgrade `requests` >2.16

**Comment by adborden** [comment]
I think this is good. Instead of an SSL error, we're getting a 404 on dev. Ready to move to production

**Comment by adborden** [comment]
Census has confirmed the fix :+1:
