### ISSUE TITLE
ckanext-archiver job cannot connect to redis

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#505]
Seeing this in the logs on harvester3p. I don't see any other messages to indicate it ever successfully connects. One issue is that harvester3p should be connecting to redis on the localhost, not harvester1p.
```
[2018-11-21 16:31:42,137: ERROR/MainProcess] Consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/lib/ckan/lib/python2.7/site-packages/celery/worker/consumer.py", line 310, in start
  File "/usr/lib/ckan/lib/python2.7/site-packages/celery/worker/consumer.py", line 326, in consume_messages
  File "/usr/lib/ckan/lib/python2.7/site-packages/kombu/connection.py", line 275, in drain_events
  File "/usr/lib/ckan/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 755, in drain_events
  File "/usr/lib/ckan/lib/python2.7/site-packages/kombu/transport/redis.py", line 279, in get
  File "/usr/lib/ckan/lib/python2.7/site-packages/kombu/transport/redis.py", line 251, in on_poll_empty
  File "/usr/lib/ckan/lib/python2.7/site-packages/kombu/transport/redis.py", line 127, in restore_visible
  File "/usr/local/lib/python2.7.10/lib/python2.7/contextlib.py", line 17, in __enter__
  File "/usr/lib/ckan/lib/python2.7/site-packages/kombu/transport/redis.py", line 65, in Mutex
  File "/usr/lib/ckan/lib/python2.7/site-packages/redis/client.py", line 1024, in setnx
  File "/usr/lib/ckan/lib/python2.7/site-packages/kombu/transport/redis.py", line 612, in execute_command
  File "/usr/lib/ckan/lib/python2.7/site-packages/redis/connection.py", line 532, in send_command
  File "/usr/lib/ckan/lib/python2.7/site-packages/redis/connection.py", line 508, in send_packed_command
  File "/usr/lib/ckan/lib/python2.7/site-packages/redis/connection.py", line 412, in connect
ConnectionError: Error 24 connecting to catalog-harvester1p.prod-ocsit.bsp.gsa.gov:6379. Too many open files.
```

**Comment by nickumia-reisys** [comment]
- https://github.com/GSA/data.gov/issues/3710
