### ISSUE TITLE
error in harvester run

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#509]
```

Traceback (most recent call last):
  File "/usr/bin/ckan", line 45, in <module>
    load_entry_point('PasteScript', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/usr/lib/ckan-new/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 127, in command
    self.run_harvester()
  File "/usr/lib/ckan-new/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 304, in run_harvester
    jobs = get_action('harvest_jobs_run')(context,{})
  File "/usr/lib/ckan-new/src/ckan/ckan/logic/__init__.py", line 430, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan-new/src/ckanext-harvest/ckanext/harvest/logic/action/update.py", line 405, in harvest_jobs_run
    {'harvest_source_id': job_obj.source_id})
AttributeError: 'NoneType' object has no attribute 'source_id'
```

**Comment by adborden** [comment]
It looks like the job existed as a running job but when queried, it no longer exists in the database.
