### ISSUE TITLE
Failed to insert duplicates into pycsw

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#596]
Seeing  a fair number of errors when loading packages into pycsw on staging.

```
2019-02-26 22:46:55,561 [__main__] ERROR: Failed to insert 3990cfea-b87f-4e65-9b08-08a4797cc9b2
Traceback (most recent call last):
  File "/usr/lib/ckan/bin/pycsw-ckan.py", line 282, in __reconcile
    repo.insert(record, 'local', util.get_today_and_now())
  File "/usr/lib/ckan-new/lib/python2.7/site-packages/pycsw/repository.py", line 294, in insert
    raise RuntimeError('ERROR: %s' % str(err.orig))
RuntimeError: ERROR: duplicate key value violates unique constraint "records_pkey"
DETAIL:  Key (identifier)=(TECHPORT_11844) already exists.
```

**Comment by adborden** [comment]
Recently USDA had a question and this issue is at the root of it. The duplicate error stops the loading cold, so pretty much no new updates are making it into pycsw.

```
2020-06-18 04:00:07,031 [pycsw-ckan] INFO: Some gathered datasets already processed already_processed=1 gathered=1000
2020-06-18 04:00:07,080 [pycsw-ckan] INFO: Found count=228 existing datasets
2020-06-18 04:00:07,081 [pycsw-ckan] INFO: Reconciling new records count=771
2020-06-18 04:00:07,081 [pycsw-ckan] DEBUG: Fetching url=https://catalog.data.gov/harvest/object/7a621610-345d-4510-8bfe-e53801bfe24c
2020-06-18 04:00:07,135 [urllib3.connectionpool] DEBUG: https://catalog.data.gov:443 "GET /harvest/object/7a621610-345d-4510-8bfe-e53801bfe24c HTTP/1.1" 200 None
2020-06-18 04:00:07,136 [pycsw-ckan] DEBUG: parsing XML as is
2020-06-18 04:00:07,136 [pycsw-ckan] DEBUG: Parsing ISO XML
2020-06-18 04:00:07,136 [pycsw.core.metadata] INFO: Serialized metadata, parsing content model
/home/pycsw/releases/20200611160545Z/.venv/lib/python2.7/site-packages/owslib/iso.py:117: FutureWarning: the .identification and .serviceidentification properties will merge into .identification being a list of properties.  This is currently implemented in .identificationinfo.  Please see https://github.com/geopython/OWSLib/issues/38 for more information
  FutureWarning)
/home/pycsw/releases/20200611160545Z/.venv/lib/python2.7/site-packages/owslib/iso.py:495: FutureWarning: The .keywords and .keywords2 properties will merge into the .keywords property in the future, with .keywords becoming a list of MD_Keywords instances. This is currently implemented in .keywords2. Please see https://github.com/geopython/OWSLib/issues/301 for more information
  FutureWarning)
2020-06-18 04:00:07,148 [pycsw.core.metadata] INFO: Scanning for links
2020-06-18 04:00:07,148 [pycsw.core.metadata] DEBUG: Scanning for gmd:transferOptions element(s)
2020-06-18 04:00:07,148 [pycsw.core.metadata] DEBUG: Scanning for gmd:distributorTransferOptions element(s)
2020-06-18 04:00:07,148 [pycsw.core.metadata] DEBUG: Scanning for srv:SV_ServiceIdentification links
Traceback (most recent call last):
  File "/home/pycsw/current/.venv/bin/pycsw-ckan.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/pycsw/releases/20200611160545Z/bin/pycsw-ckan.py", line 424, in <module>
    __reconcile(gathered_records, existing_records)
  File "/home/pycsw/releases/20200611160545Z/bin/pycsw-ckan.py", line 288, in __reconcile
    repo.insert(record, 'local', util.get_today_and_now())
  File "/home/pycsw/releases/20200611160545Z/pycsw/core/repository.py", line 304, in insert
    self.session.commit()
  File "/home/pycsw/releases/20200611160545Z/.venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/home/pycsw/releases/20200611160545Z/.venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/home/pycsw/releases/20200611160545Z/.venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
    self.session.flush()
  File "/home/pycsw/releases/20200611160545Z/.venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2459, in flush
    self._flush(objects)
  File "/home/pycsw/releases/20200611160545Z/.venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/pycsw/releases/20200611160545Z/.venv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/pycsw/releases/20200611160545Z/.venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2557, in _flush
    flush_context.execute()
  File "/home/pycsw/releases/20200611160545Z/.venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/pycsw/releases/20200611160545Z/.venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/pycsw/releases/20200611160545Z/.venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/home/pycsw/releases/20200611160545Z/.venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1084, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "/home/pycsw/releases/20200611160545Z/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/pycsw/releases/20200611160545Z/.venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/pycsw/releases/20200611160545Z/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/pycsw/releases/20200611160545Z/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/pycsw/releases/20200611160545Z/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/pycsw/releases/20200611160545Z/.venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/pycsw/releases/20200611160545Z/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/pycsw/releases/20200611160545Z/.venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "records_pkey"
DETAIL:  Key (identifier)=(54364D59-BAE4-4C9D-B122-AB0AE7122F92) already exists.

[SQL: INSERT INTO records (identifier, typename, schema, mdsource, insert_date, xml, anytext, language, type, title, title_alternate, abstract, keywords, keywordstype, parentidentifier, relation, time_begin, time_end, topicategory, resourcelanguage, creator, publisher, contributor, organization, securityconstraints, accessconstraints, otherconstraints, date, date_revision, date_creation, date_publication, date_modified, format, source, crs, geodescode, denominator, distancevalue, distanceuom, wkt_geometry, servicetype, servicetypeversion, operation, couplingtype, operateson, operatesonidentifier, operatesoname, degree, classification, conditionapplyingtoaccessanduse, lineage, responsiblepartyrole, specificationtitle, specificationdate, specificationdatetype, links, ckan_id, ckan_modified, ckan_collection, anytext_tsvector, wkb_geometry) VALUES (%(identifier)s, %(typename)s, %(schema)s, %(mdsource)s, %(insert_date)s, %(xml)s, %(anytext)s, %(language)s, %(type)s, %(title)s, %(title_alternate)s, %(abstract)s, %(keywords)s, %(keywordstype)s, %(parentidentifier)s, %(relation)s, %(time_begin)s, %(time_end)s, %(topicategory)s, %(resourcelanguage)s, %(creator)s, %(publisher)s, %(contributor)s, %(organization)s, %(securityconstraints)s, %(accessconstraints)s, %(otherconstraints)s, %(date)s, %(date_revision)s, %(date_creation)s, %(date_publication)s, %(date_modified)s, %(format)s, %(source)s, %(crs)s, %(geodescode)s, %(denominator)s, %(distancevalue)s, %(distanceuom)s, %(wkt_geometry)s, %(servicetype)s, %(servicetypeversion)s, %(operation)s, %(couplingtype)s, %(operateson)s, %(operatesonidentifier)s, %(operatesoname)s, %(degree)s, %(classification)s, %(conditionapplyingtoaccessanduse)s, %(lineage)s, %(responsiblepartyrole)s, %(specificationtitle)s, %(specificationdate)s, %(specificationdatetype)s, %(links)s, %(ckan_id)s, %(ckan_modified)s, %(ckan_collection)s, %(anytext_tsvector)s, %(wkb_geometry)s)]
[parameters: {'responsiblepartyrole': 'pointOfContact', 'date_revision': None, 'otherconstraints': 'https://edg.epa.gov/EPA_Data_License.html', 'accessconstraints': 'licenseUnrestricted', 'distancevalue': None, 'classification': None, 'creator': None, 'abstract': 'Layer for displaying areas in New York State that are of interest to Region 2 Haudenosaunee tribes for consultation on environmental issues. The boun ... (279 characters truncated) ... ce1.r02.epa.gov/QuickPlace/r2gis/Main.nsf/$defaultview/50AA19DAB434F06685257154004F8180/$File/indiannation_land_claim_areas_time_life.jpg?OpenElement', 'servicetypeversion': None, 'geodescode': None, 'time_end': None, 'keywords': 'Region 2,New York,EPAR2GIS,adminbndEPAR2GIS,basemapEPAR2GIS,Oracle Spatial,environment,County,NEPA,Environment,environment,020:053,Downloadable Data', 'operatesoname': None, 'date_publication': '2008-03-06', 'relation': None, 'wkb_geometry': None, 'contributor': None, 'couplingtype': None, 'operation': None, 'conditionapplyingtoaccessanduse': 'EPA Public Domain License', 'insert_date': '2020-06-18T04:00:07Z', 'xml': '<gmd:MD_Metadata xmlns="http://www.isotc211.org/2005/gmd" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gco="http://www.isotc211.org/2005/gco" x ... (21555 characters truncated) ... ateFrequency><dateOfNextUpdate><gco:Date>2012-03-06</gco:Date></dateOfNextUpdate></MD_MaintenanceInformation></metadataMaintenance></gmd:MD_Metadata>', 'parentidentifier': None, 'servicetype': '', 'keywordstype': 'place', 'operatesonidentifier': None, 'ckan_modified': u'2018-01-12T15:55:06.727Z', 'time_begin': None, 'ckan_id': u'7d5cbfa1-e911-418a-b2de-7081e587ef7e', 'links': None, 'securityconstraints': 'unclassified', 'wkt_geometry': 'POLYGON((-79.76 41.41, -79.76 45.01, -73.21 45.01, -73.21 41.41, -79.76 41.41))', 'mdsource': 'local', 'type': 'dataset', 'operateson': None, 'schema': 'http://www.isotc211.org/2005/gmd', 'degree': None, 'format': None, 'resourcelanguage': None, 'denominator': None, 'date': '2017-09-19', 'date_creation': None, 'specificationdatetype': None, 'lineage': None, 'crs': 'urn:ogc:def:crs:EPSG:6.11:4296', 'ckan_collection': True, 'language': None, 'date_modified': '2017-09-19', 'anytext_tsvector': None, 'distanceuom': None, 'title_alternate': None, 'title': 'Haudenosaunee Territory for Consultation Purposes (EPA.TRIBCONSULTBND_R2)', 'anytext': '54364D59-BAE4-4C9D-B122-AB0AE7122F92 eng utf8 dataset Linda Timander U.S. Environmental Protection Agency, Region 2, GIS Team GIS Analyst (212) 637-3 ... (2622 characters truncated) ... oundaries roughly delineated by heads up digitizing 2006-01-01T00:00:00 Imported into Region 2 Oracle database 2008-03-06T00:00:00 unknown 2012-03-06', 'specificationtitle': None, 'typename': 'gmd:MD_Metadata', 'specificationdate': None, 'source': None, 'topicategory': 'environment', 'publisher': 'U.S. Environmental Protection Agency, Region 2, GIS Team', 'organization': 'U.S. Environmental Protection Agency, Region 2, GIS Team', 'identifier': '54364D59-BAE4-4C9D-B122-AB0AE7122F92'}]
(Background on this error at: http://sqlalche.me/e/gkpj)
```

**Comment by jbrown-xentity** [comment]
The changes involve updates in error handling. So far after 3+ hours of harvesting, only the single EPA duplicate was found (you can see the datasets in the catalog [here](https://catalog.data.gov/dataset/haudenosaunee-territory-for-consultation-purposes-epa-tribconsultbnd-r2b9f06) and [here](https://catalog.data.gov/dataset/haudenosaunee-territory-for-consultation-purposes-epa-tribconsultbnd-r2d4ff1)). Marking fix as ready for deploy.
