### ISSUE TITLE
PyCSW load fails to insert records due to field size for ix_records_othercontraints

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#606]
```
2019-03-01 22:43:58,989 [pycsw-ckan] ERROR: Failed to insert 9bbec414-026b-42e9-9bb9-a0e378830c61
Traceback (most recent call last):
  File "/usr/lib/ckan/bin/pycsw-ckan.py", line 289, in __reconcile
    repo.insert(record, 'local', util.get_today_and_now())
  File "/usr/lib/ckan/lib/python2.7/site-packages/pycsw/repository.py", line 294, in insert
    raise RuntimeError('ERROR: %s' % str(err.orig))
RuntimeError: ERROR: index row size 2848 exceeds maximum 2712 for index "ix_records_otherconstraints"
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.
```

**Comment by adborden** [comment]
For the ix_records_abstract index:
```
2019-03-01 22:49:34,118 [pycsw-ckan] ERROR: Failed to insert aec8722b-6d07-47cf-b096-2ccd47e103d4
Traceback (most recent call last):
  File "/usr/lib/ckan/bin/pycsw-ckan.py", line 289, in __reconcile
    repo.insert(record, 'local', util.get_today_and_now())
  File "/usr/lib/ckan/lib/python2.7/site-packages/pycsw/repository.py", line 294, in insert
    raise RuntimeError('ERROR: %s' % str(err.orig))
RuntimeError: ERROR: index row size 2784 exceeds maximum 2712 for index "ix_records_abstract"
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.
```

For the ix_records_keywords index:
```
2019-03-01 22:49:47,011 [pycsw-ckan] ERROR: Failed to insert 9d9fe91e-da81-4488-bb02-8adf66b6182d
Traceback (most recent call last):
  File "/usr/lib/ckan/bin/pycsw-ckan.py", line 289, in __reconcile
    repo.insert(record, 'local', util.get_today_and_now())
  File "/usr/lib/ckan/lib/python2.7/site-packages/pycsw/repository.py", line 294, in insert
    raise RuntimeError('ERROR: %s' % str(err.orig))
RuntimeError: ERROR: index row size 2792 exceeds maximum 2712 for index "ix_records_keywords"
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.
```

**Comment by adborden** [comment]
Hmm, assuming we're using the pycsw api correctly, this might actually be a bug upstream.

**Comment by adborden** [comment]
No progress on upstream https://github.com/geopython/pycsw/issues/398

**Comment by adborden** [comment]
Also related https://github.com/geopython/pycsw/issues/470

**Comment by adborden** [comment]
This is still happening in 2.4.0

**Comment by adborden** [comment]
Work around is to drop these indexes and rely on the full text search index.
```sql
DROP INDEX ix_records_abstract;
DROP INDEX ix_records_keywords;
DROP INDEX ix_records_otherconstraints;
```

**Comment by nickumia-reisys** [comment]
No more Pycsw,
- https://github.com/GSA/data.gov/issues/3182
