### ISSUE TITLE
pycsw on staging fails with certificate error

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#628]
```
2019-03-07 01:28:13,636 [pycsw.config] DEBUG: Initializing static context
2019-03-07 01:28:13,644 [requests.packages.urllib3.connectionpool] INFO: Starting new HTTPS connection (1): catalog-datagov.dev-ocsit.bsp.gsa.gov
Fetching tags from https://catalog-datagov.dev-ocsit.bsp.gsa.gov/
Traceback (most recent call last):
 File "/usr/lib/ckan/bin/pycsw-ckan.py", line 452, in <module>
   response = requests.get(url)
 File "/usr/lib/ckan-new/lib/python2.7/site-packages/requests/api.py", line 68, in get
   return request('get', url, **kwargs)
 File "/usr/lib/ckan-new/lib/python2.7/site-packages/requests/api.py", line 50, in request
   response = session.request(method=method, url=url, **kwargs)
 File "/usr/lib/ckan-new/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
   resp = self.send(prep, **send_kwargs)
 File "/usr/lib/ckan-new/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
   r = adapter.send(request, **kwargs)
 File "/usr/lib/ckan-new/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
   raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

This is because staging uses an internal certificate. The internal CA is already installed on the host, we just need to set an environment for pycsw jobs: `REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt`. This is only for the staging environment.

**Comment by adborden** [comment]
This is fixed in https://github.com/GSA/datagov-deploy/pull/898
