### ISSUE TITLE
Catalog CKAN tracking update fails, out of temporary database space

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#707]
As part of investigation for the [metrics report](https://github.com/GSA/datagov-deploy/issues/655), I found that the tracking update job fails on production with a database error. This could be indicative that we are running low on space in our database.

```
2019-04-05 07:06:41.054180 tracking updated for 2019-03-01 00:00:00
Traceback (most recent call last):
 File "/usr/bin/ckan", line 45, in <module>
   load_entry_point('PasteScript', 'console_scripts', 'paster')()
 File "/usr/lib/ckan/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
   invoke(command, command_name, options, args[1:])
 File "/usr/lib/ckan/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
   exit_code = runner.run(args)
 File "/usr/lib/ckan/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
   result = self.command()
 File "/usr/lib/ckan-new/src/ckan/ckan/lib/cli.py", line 1127, in command
   self.update_all(engine, start_date)
 File "/usr/lib/ckan-new/src/ckan/ckan/lib/cli.py", line 1164, in update_all
   self.update_tracking(engine, start_date)
 File "/usr/lib/ckan-new/src/ckan/ckan/lib/cli.py", line 1268, in update_tracking
   engine.execute(sql)
 File "/usr/lib/ckan/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1690, in execute
   return connection.execute(statement, *multiparams, **params)
 File "/usr/lib/ckan/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 719, in execute
   return self._execute_text(object, multiparams, params)
 File "/usr/lib/ckan/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 868, in _execute_text
   statement, parameters
 File "/usr/lib/ckan/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 954, in _execute_context
   context)
 File "/usr/lib/ckan/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1116, in _handle_dbapi_exception
   exc_info
 File "/usr/lib/ckan/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
   reraise(type(exception), exception, tb=exc_tb)
 File "/usr/lib/ckan/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 947, in _execute_context
   context)
 File "/usr/lib/ckan/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 435, in do_execute
   cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (OperationalError) could not write block 281485 of temporary file: No space left on device
"WITH t2 AS  (\n                    SELECT package_id, max(tracking_date) AS max_date\n                    FROM tracking_summary\n                    GROUP BY package_id\n                    HAVING max(tracking_date) < '2019-03-02 00:00:00'\n                  ), t3 AS (\n                    SELECT t1.url, t1.package_id,t1.tracking_type\n                    FROM tracking_summary t1\n                    JOIN t2\n                    ON\n                      t1.package_id = t2.package_id\n                    AND\n                      t1.tracking_date = t2.max_date\n                    WHERE t1.recent_views > 0\n                  ), t4 AS (\n                    SELECT * from t3 GROUP BY url, package_id, tracking_type\n                  )\n                INSERT INTO tracking_summary\n                  (url, package_id, count, tracking_date, tracking_type)\n                SELECT url, package_id, 0, '2019-03-02 00:00:00', tracking_type\n                FROM t4\n                WHERE url NOT IN (SELECT url FROM tracking_summary WHERE tracking_date = '2019-03-02 00:00:00');\n                COMMIT;" {}
```

## How to reproduce
1. `sudo ckan tracking update`

## Expected result

Job completes successfully and updates tracking data.

## Actual result

Job fails with OperationError.

**Comment by adborden** [comment]
We've opened an issue with BSP to upgrade the database instance size. We need to [re-enable our cleanup jobs](https://github.com/GSA/datagov-deploy/issues/499) to ensure the database isn't growing faster than necessary.

**Comment by adborden** [comment]
This was resolved with the database upgrade.
