### ISSUE TITLE
catalog-web bionic 500 from missing m2crypto API

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#758]
pysaml2 depends on an old version of m2crypto. The older versions of m2crypto do not build on bionic.

```
[Fri Apr 19 18:35:01.852140 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664] Traceback (most recent call last):
[Fri Apr 19 18:35:01.852160 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]   File "/etc/ckan/apache.wsgi", line 10, in <module>
[Fri Apr 19 18:35:01.852185 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]     application = loadapp('config:%s' % config_filepath)
[Fri Apr 19 18:35:01.852194 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]   File "/usr/lib/ckan/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
[Fri Apr 19 18:35:01.852215 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]     return loadobj(APP, uri, name=name, **kw)
[Fri Apr 19 18:35:01.852223 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]   File "/usr/lib/ckan/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
[Fri Apr 19 18:35:01.852233 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]     return context.create()
[Fri Apr 19 18:35:01.852240 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]   File "/usr/lib/ckan/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
[Fri Apr 19 18:35:01.852250 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]     return self.object_type.invoke(self)
[Fri Apr 19 18:35:01.852256 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]   File "/usr/lib/ckan/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
[Fri Apr 19 18:35:01.852266 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]     return fix_call(context.object, context.global_conf, **context.local_conf)
[Fri Apr 19 18:35:01.852273 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]   File "/usr/lib/ckan/lib/python2.7/site-packages/paste/deploy/util.py", line 56, in fix_call
[Fri Apr 19 18:35:01.852283 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]     val = callable(*args, **kw)
[Fri Apr 19 18:35:01.852290 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]   File "/usr/lib/ckan-new/src/ckan/ckan/config/middleware.py", line 118, in make_app
[Fri Apr 19 18:35:01.852301 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]     who_parser.parse(open(app_conf['who.config_file']))
[Fri Apr 19 18:35:01.852308 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]   File "/usr/lib/ckan/lib/python2.7/site-packages/repoze/who/config.py", line 80, in parse
[Fri Apr 19 18:35:01.852375 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]     obj = self._makePlugin(name, IPlugin, options)
[Fri Apr 19 18:35:01.852385 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]   File "/usr/lib/ckan/lib/python2.7/site-packages/repoze/who/config.py", line 37, in _makePlugin
[Fri Apr 19 18:35:01.852407 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]     obj = _resolve(name)
[Fri Apr 19 18:35:01.852414 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]   File "/usr/lib/ckan/lib/python2.7/site-packages/repoze/who/config.py", line 20, in _resolve
[Fri Apr 19 18:35:01.852423 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]     return EntryPoint.parse('x=%s' % name).load(False)
[Fri Apr 19 18:35:01.852430 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]   File "/usr/lib/ckan/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2343, in load
[Fri Apr 19 18:35:01.852865 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]     return self.resolve()
[Fri Apr 19 18:35:01.852876 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]   File "/usr/lib/ckan/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2349, in resolve
[Fri Apr 19 18:35:01.852889 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]     module = __import__(self.module_name, fromlist=['__name__'], level=0)
[Fri Apr 19 18:35:01.852896 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]   File "/usr/lib/ckan-new/src/pysaml2/src/s2repoze/plugins/sp.py", line 40, in <module>
[Fri Apr 19 18:35:01.853008 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]     from saml2 import ecp, BINDING_HTTP_REDIRECT
[Fri Apr 19 18:35:01.853018 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]   File "/usr/lib/ckan-new/src/pysaml2/src/saml2/ecp.py", line 32, in <module>
[Fri Apr 19 18:35:01.853072 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]     from saml2.server import Server
[Fri Apr 19 18:35:01.853084 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]   File "/usr/lib/ckan-new/src/pysaml2/src/saml2/server.py", line 29, in <module>
[Fri Apr 19 18:35:01.853189 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]     from saml2.entity import Entity
[Fri Apr 19 18:35:01.853199 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]   File "/usr/lib/ckan-new/src/pysaml2/src/saml2/entity.py", line 4, in <module>
[Fri Apr 19 18:35:01.853333 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]     from saml2.metadata import ENDPOINTS
[Fri Apr 19 18:35:01.853342 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]   File "/usr/lib/ckan-new/src/pysaml2/src/saml2/metadata.py", line 14, in <module>
[Fri Apr 19 18:35:01.853443 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]     from saml2.sigver import pre_signature_part
[Fri Apr 19 18:35:01.853452 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]   File "/usr/lib/ckan-new/src/pysaml2/src/saml2/sigver.py", line 350, in <module>
[Fri Apr 19 18:35:01.853628 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664]     from M2Crypto.__m2crypto import bn_to_mpi
[Fri Apr 19 18:35:01.853647 2019] [wsgi:error] [pid 746:tid 140104279365376] [remote 127.0.0.1:45664] ImportError: No module named __m2crypto
```

## How to reproduce

1. Start apache2 on catalog-web bionic
1. `curl localhost`

## Expected behavior

Successful response

## Actual behavior

500 with above stack trace in `/var/log/apache2/ckan.error.log`

**Comment by adborden** [comment]
Work around is to run the ckan-native-login playbook to disable the saml2 plugin.

**Comment by adborden** [comment]
I was able to work around by tweaking [pysaml2's](https://github.com/GSA/pysaml2/commit/f527b8f7487c29a44205eb7ee05956512ba216cf) use of the private M2Crytpo API.
